In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../../data/meta/peptides_by_protein.csv")
df

,protein,1_peptides,1_peptides_no_match_sp,2_peptides,2_peptides_no_match_sp,3_peptides_proteotypic,3_peptides_not_proteotypic,4_peptides,4_peptides_no_match_sp
0,ENST00000291041_23_121,NaN,NaN,NaN,NaN,NaN,NaN,AAAAAAAAIAR,AAAAAAAAIAR
1,ENST00000303204_18_68,NaN,NaN,NaN,NaN,NaN,NaN,AAAAAAAAWAR;AAAAAAAWAR,AAAAAAAAWAR;AAAAAAAWAR
2,ENSG00000112658__ENST00000265354__uORF__2__ATG,NaN,NaN,NaN,NaN,NaN,NaN,AAAAAAPIPR;AAAAAPIPR;MAAAAAAPIPR,AAAAAAPIPR;AAAAAPIPR;MAAAAAAPIPR
3,ENST00000604259_1_273,FFQSFSDALIDQDPQAALEELTK,FFQSFSDALIDQDPQAALEELTK,LEELTKALEQKP,NaN,NaN,NaN,NaN,NaN
4,TCONS_00021881_241_567,NaN,NaN,NaN,NaN,NaN,NaN,SVIGNLGGGAK,SVIGNLGGGAK
...,...,...,...,...,...,...,...,...,...
906,TCONS_00012546_485_562,NaN,NaN,NaN,NaN,NaN,NaN,MYISSNGLWVR;YISSNGLWVR,MYISSNGLWVR;YISSNGLWVR
907,ENST00000578759_764_3556,AIQHWLTESAR;ALLEFAQGR;ASDPAAYVSHLPVHQDGSCNGLQH...,NaN,AIQHWLTESAR;ASDPAAYVSHLPVHQDGSCNGLQHYAALGR;CLE...,VSAQVQALQNHYR,NaN,NaN,ITYTHNGDISR;QVLEGFITR;RVLDLVLQL,NaN
908,ENSG00000162631__TCONS_00010433__ncRNA__10__ATG,NaN,NaN,NaN,NaN,NaN,NaN,RAIALLNYY,RAIALLNYY
909,ENSG00000041880__TCONS_00610801__ncRNA__3__CTG,NaN,NaN,NaN,NaN,NaN,NaN,LCFTPLVAK,LCFTPLVAK
910,ENSG00000278834__ENST00000619697__ncRNA__1__TTG,NaN,NaN,NaN,NaN,NaN,NaN,VLYEGLESK,VLYEGLESK

In [4]:
hlala = pd.read_csv("HLA_la_reported_cryptic_peptides_with_metadata.csv")
hlala

,Delta first,Decoy,Genome,Location,Category,Sequence,Delta next,spectra,Top location count,PEP,...,rank.peptide.redundancy,Sequence.nr,number.patients.shared,patients,best.Q,tissue,best HLA binder,best.peptide,best.ALC,modified
0,0,T,h.ens90,6-:24720379-24720406,UTR5,SAGGPVTVR,100,33,1,0.003110,...,1,SAGGPVTVR,3,"ZH_02, ZH_08, ZH_09",0.00000,Cerebellum,strong binder,yes,99,unmodified
1,0,T,h.ens90,17-:31296310-31296337,UTR5,ALMEYQILK,100,18,1,0.003110,...,1,ALMEYQILK,3,"ZH_02, ZH_06, ZH_13",0.00245,Cerebellum,strong binder,yes,99,modified
2,0,T,h.ens90,16+:3311900-3311927,UTR5,SSAGILIKR,100,10,1,0.003110,...,1,SSAGILIKR,2,"ZH_02, ZH_08",0.00245,Brain,strong binder,yes,99,unmodified
3,0,T,h.ens90,3-:101493900-101493927,OffFrame,SITTVQIQK,100,35,1,0.035600,...,1,SITTVQIQK,4,"ZH_02, ZH_05, ZH_12, ZH_13",0.01330,Brain,strong binder,yes,94,unmodified
4,0,T,h.ens90,6-:26056172-26056202,OffFrame,TTAVSNLVSR,100,59,1,0.000774,...,1,TTAVSNLVSR,3,"ZH_02, ZH_08, ZH_09",0.00000,Brain,strong binder,yes,99,unmodified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1402,0,T,h.ens90,9-:108931102-108931129,OffFrame,ISDPGVQGY,100,7,1,0.082000,...,1,ISDPGVQGY,5,"ZH_05, ZH_11, ZH_15, T5, T6",0.04160,Thymus,strong binder,yes,83,unmodified
1403,12,T,h.ens90,15+:78878236-78878259|78880511-78880515,UTR5,GLFFMKQSV,100,6,1,0.104000,...,1,GLFFMKQSV,3,"ZH_09, ZH_15, T6",0.04940,Thymus,strong binder,yes,77,unmodified
1404,0,T,h.ens90,14+:22464277-22464304,OffFrame,VAVNFLLTA,100,4,1,0.094800,...,1,VAVNFLLTA,1,T6,0.04810,Thymus,weak binder,yes,81,unmodified
1405,1,T,h.ens90,14+:74713224-74713251,UTR5,DVIRPLFGW,100,2,1,0.060400,...,1,DVIRPLFGW,2,"T3, T6",0.01270,Thymus,strong binder,yes,84,unmodified
1406,0,T,h.ens90,1-:8013883-8013910,OffFrame,EVSQIQILL,100,1,1,0.129000,...,1,EVSQIQILL,1,T6,0.06210,Thymus,strong binder,yes,77,unmodified

In [6]:
metadata = pd.read_csv("../../data/meta/20260219_EwS_ncORF_metadata_summary.tsv", sep="\t")
metadata

,orf_id,ORF_ranges,Protein,gene_id,gene_biotype,gene_name,transcript_id,uniprot_gn_ids,cl_mean,ps_mean,...,Number_SB,Peptides_WB,Number_WB,class,any_peptide_found_in_IP,result_A673,result_SKNMC,result_MHHES,result_TC106,result_RDES
0,ENSG00000159167__ENST00000290271__uORF__2__GTG,8:23854633-23854746,MAAAAAAAAAAAAAEAPVAAAASPATTTKKNPHQILT,ENSG00000159167,protein_coding,STC1,ENST00000290271,A0A0H3W641;P52823,1.187192,2.508946,...,NaN,NaN,NaN,0.0,False,not expressed,not expressed,upregulated,ns,ns
1,ENST00000291041_23_121,16:67893276-67908682,MAAAAAAAAAAAIARRWPAEPPRRRRARRPREV,ENSG00000159792,protein_coding,PSKH1,ENST00000291041,P11801;A0A087WZT9,23.079040,17.597305,...,NaN,NaN,NaN,1.0,True,ns,ns,ns,ns,ns
2,ENST00000216727_182_1099,14:23321470-23325283,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...,ENSG00000100836,protein_coding,PABPN1,ENST00000216727,B4DEH8;Q86U42;G3V4T2,72.570950,51.634440,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ENST00000397276_14_901,14:23321470-23324296,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...,ENSG00000100836,protein_coding,PABPN1,ENST00000397276,B4DEH8;Q86U42;G3V4T2,71.136807,50.211111,...,NaN,NaN,NaN,NaN,NaN,ns,ns,ns,ns,ns
4,ENST00000354300_17_85,12:110583234-110583302,MAAAAAAAAAGTSVGLRRRSRRF,ENSG00000196850,protein_coding,PPTC7,ENST00000354300,Q8NI37,14.741234,14.913901,...,NaN,NaN,NaN,0.0,False,not expressed,ns,upregulated,ns,ns
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62178,ENSG00000116604__TCONS_00065632__ncRNA__9__ATT,1:156483398-156500599,MYYSPRPELRLPGVEDPPDQGRGLPALCRDNTVPPAGLEAVQKVSCRP,ENSG00000116604,protein_coding,MEF2D,TCONS_00065632,Q14814;Q05BX2,12.438524,33.178861,...,NaN,NaN,NaN,0.0,False,ns,ns,ns,ns,ns
62179,ENST00000552151_8_454,12:70310970-70330470,MYYSQSSMFPHRSEKDMLASPSTSGQLSQFGASLYGQQSALGLPMR...,ENSG00000111596,protein_coding,CNOT2,ENST00000552151,F8VSK9;Q9NZN8;F8VUB4;F8W145;F8VPX5;F8VVY1;F8VV...,12.182117,23.360930,...,NaN,NaN,NaN,NaN,NaN,ns,ns,ns,ns,ns
62180,ENST00000495930_268_459,13:112875798-112875989,MYYVFIQMLSSGPAWLAIVLLVTISLLPDVLKKVLCRQLWPTATER...,ENSG00000068650,protein_coding,ATP11A,ENST00000495930,P98196;E9PEJ6;A2A3G9;A0A087WVE8,6.739418,19.103163,...,NaN,NaN,NaN,NaN,NaN,not expressed,ns,ns,ns,ns
62181,ENSG00000181392_ENSG00000239382__ENST000004904...,19:36010923-36013077,MYYVPDFISKEEEEYLLRQVFNAPKPKWTQLSGRKLQNWGPHCLPQ...,ENSG00000239382,protein_coding,ALKBH6,ENST00000490483,Q3KRA9;E9PI76;S4R3C7;H0YD83,10.796175,7.697037,...,NaN,NaN,NaN,NaN,NaN,ns,ns,ns,ns,ns
62182,ENST00000507377_491_1471,4:128091430-128122230,MYYYDDGTGVQVYPVEEALLKEYIKRQIEYYFSVENLERDFFLRGK...,ENSG00000138709,protein_coding,LARP1B,ENST00000507377,Q659C4;G3V0E9;A0A994J4X5;D6RJB0;A0A994J4H9;D6R...,2.507563,3.846579,...,NaN,NaN,NaN,NaN,NaN,ns,ns,ns,ns,ns

In [7]:
hlala['coordinates'] = hlala['Location']
hlala['coordinates'] = hlala['coordinates'].apply(lambda x: x.replace('-:', ':').replace('+:', ':'))
hlala['coordinates'] = hlala['coordinates'].apply(lambda x: x.replace('|', '|'+x[:x.index(':')]+':') if '|' in x else x)
hlala['coordinates'] = hlala['coordinates'].apply(lambda x: x.split('|') if '|' in x else [x])
hlala = hlala.explode('coordinates')
hlala

,Delta first,Decoy,Genome,Location,Category,Sequence,Delta next,spectra,Top location count,PEP,...,Sequence.nr,number.patients.shared,patients,best.Q,tissue,best HLA binder,best.peptide,best.ALC,modified,coordinates
0,0,T,h.ens90,6-:24720379-24720406,UTR5,SAGGPVTVR,100,33,1,0.003110,...,SAGGPVTVR,3,"ZH_02, ZH_08, ZH_09",0.00000,Cerebellum,strong binder,yes,99,unmodified,6:24720379-24720406
1,0,T,h.ens90,17-:31296310-31296337,UTR5,ALMEYQILK,100,18,1,0.003110,...,ALMEYQILK,3,"ZH_02, ZH_06, ZH_13",0.00245,Cerebellum,strong binder,yes,99,modified,17:31296310-31296337
2,0,T,h.ens90,16+:3311900-3311927,UTR5,SSAGILIKR,100,10,1,0.003110,...,SSAGILIKR,2,"ZH_02, ZH_08",0.00245,Brain,strong binder,yes,99,unmodified,16:3311900-3311927
3,0,T,h.ens90,3-:101493900-101493927,OffFrame,SITTVQIQK,100,35,1,0.035600,...,SITTVQIQK,4,"ZH_02, ZH_05, ZH_12, ZH_13",0.01330,Brain,strong binder,yes,94,unmodified,3:101493900-101493927
4,0,T,h.ens90,6-:26056172-26056202,OffFrame,TTAVSNLVSR,100,59,1,0.000774,...,TTAVSNLVSR,3,"ZH_02, ZH_08, ZH_09",0.00000,Brain,strong binder,yes,99,unmodified,6:26056172-26056202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,12,T,h.ens90,15+:78878236-78878259|78880511-78880515,UTR5,GLFFMKQSV,100,6,1,0.104000,...,GLFFMKQSV,3,"ZH_09, ZH_15, T6",0.04940,Thymus,strong binder,yes,77,unmodified,15:78878236-78878259
1403,12,T,h.ens90,15+:78878236-78878259|78880511-78880515,UTR5,GLFFMKQSV,100,6,1,0.104000,...,GLFFMKQSV,3,"ZH_09, ZH_15, T6",0.04940,Thymus,strong binder,yes,77,unmodified,15:78880511-78880515
1404,0,T,h.ens90,14+:22464277-22464304,OffFrame,VAVNFLLTA,100,4,1,0.094800,...,VAVNFLLTA,1,T6,0.04810,Thymus,weak binder,yes,81,unmodified,14:22464277-22464304
1405,1,T,h.ens90,14+:74713224-74713251,UTR5,DVIRPLFGW,100,2,1,0.060400,...,DVIRPLFGW,2,"T3, T6",0.01270,Thymus,strong binder,yes,84,unmodified,14:74713224-74713251
1406,0,T,h.ens90,1-:8013883-8013910,OffFrame,EVSQIQILL,100,1,1,0.129000,...,EVSQIQILL,1,T6,0.06210,Thymus,strong binder,yes,77,unmodified,1:8013883-8013910

In [8]:
merge = metadata.merge(hlala, left_on='ORF_ranges', right_on='coordinates')
merge

Empty DataFrame
Columns: [orf_id, ORF_ranges, Protein, gene_id, gene_biotype, gene_name, transcript_id, uniprot_gn_ids, cl_mean, ps_mean, ps_n_translated, ps_translated, translated_A673, translated_SKNMC, translated_MHHES1, translated_RDES, translated_TC106, EwS_specific, orf_category_new, same_as_orfquant, same_as_orfquant_start, neotranscript_orf_type, neotranscript_type, isoform_final, distance_chip, distance_msat, peak_orth_near, ggaa_near, Peptides_SB, Number_SB, Peptides_WB, Number_WB, class, any_peptide_found_in_IP, result_A673, result_SKNMC, result_MHHES, result_TC106, result_RDES, Delta first, Decoy, Genome, Location, Category, Sequence, Delta next, spectra, Top location count, PEP, Q, Hydrophobicity, Intensity, Gene, Symbol, ORF TIS prio, ORF TIS, ORF length (nt), ORF nterm (aa), ORF cterm (aa), Region nterm, Region length, Region cterm, Intron index, Upstream sequence, Downstream sequence, HLA allele, netMHC % rank, cryptic, HLA binder, filtered.HLA allele, end.at.stop, rank.peptide.redundancy, Sequence.nr, number.patients.shared, patients, best.Q, tissue, best HLA binder, best.peptide, best.ALC, modified, coordinates]
Index: []

[0 rows x 82 columns]

In [ ]:
#no overlap on the coordinate level, could be because of different references used

In [9]:
df_merge = df.merge(metadata, left_on='protein', right_on='orf_id')
df_merge

,protein,1_peptides,1_peptides_no_match_sp,2_peptides,2_peptides_no_match_sp,3_peptides_proteotypic,3_peptides_not_proteotypic,4_peptides,4_peptides_no_match_sp,orf_id,...,Number_SB,Peptides_WB,Number_WB,class,any_peptide_found_in_IP,result_A673,result_SKNMC,result_MHHES,result_TC106,result_RDES
0,ENST00000291041_23_121,NaN,NaN,NaN,NaN,NaN,NaN,AAAAAAAAIAR,AAAAAAAAIAR,ENST00000291041_23_121,...,NaN,NaN,NaN,1.0,True,ns,ns,ns,ns,ns
1,ENST00000303204_18_68,NaN,NaN,NaN,NaN,NaN,NaN,AAAAAAAAWAR;AAAAAAAWAR,AAAAAAAAWAR;AAAAAAAWAR,ENST00000303204_18_68,...,NaN,NaN,NaN,1.0,True,not expressed,ns,upregulated,ns,ns
2,ENSG00000112658__ENST00000265354__uORF__2__ATG,NaN,NaN,NaN,NaN,NaN,NaN,AAAAAAPIPR;AAAAAPIPR;MAAAAAAPIPR,AAAAAAPIPR;AAAAAPIPR;MAAAAAAPIPR,ENSG00000112658__ENST00000265354__uORF__2__ATG,...,NaN,NaN,NaN,1.0,True,not expressed,downregulated,ns,ns,downregulated
3,ENST00000604259_1_273,FFQSFSDALIDQDPQAALEELTK,FFQSFSDALIDQDPQAALEELTK,LEELTKALEQKP,NaN,NaN,NaN,NaN,NaN,ENST00000604259_1_273,...,NaN,NaN,NaN,0.0,False,not expressed,not expressed,ns,downregulated,ns
4,TCONS_00021881_241_567,NaN,NaN,NaN,NaN,NaN,NaN,SVIGNLGGGAK,SVIGNLGGGAK,TCONS_00021881_241_567,...,NaN,NaN,NaN,0.0,False,ns,ns,downregulated,ns,ns
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
906,TCONS_00012546_485_562,NaN,NaN,NaN,NaN,NaN,NaN,MYISSNGLWVR;YISSNGLWVR,MYISSNGLWVR;YISSNGLWVR,TCONS_00012546_485_562,...,6.0,"SNGLWVRRVSL,WVRRVSLPSVL,RRVSLPSVLCA,SLPSVLCAVT...",16.0,1.0,True,ns,ns,ns,ns,ns
907,ENST00000578759_764_3556,AIQHWLTESAR;ALLEFAQGR;ASDPAAYVSHLPVHQDGSCNGLQH...,NaN,AIQHWLTESAR;ASDPAAYVSHLPVHQDGSCNGLQHYAALGR;CLE...,VSAQVQALQNHYR,NaN,NaN,ITYTHNGDISR;QVLEGFITR;RVLDLVLQL,NaN,ENST00000578759_764_3556,...,NaN,NaN,NaN,0.0,False,ns,ns,ns,ns,ns
908,ENSG00000162631__TCONS_00010433__ncRNA__10__ATG,NaN,NaN,NaN,NaN,NaN,NaN,RAIALLNYY,RAIALLNYY,ENSG00000162631__TCONS_00010433__ncRNA__10__ATG,...,14.0,"YNGRAIALLNY,GRAIALLNYYL,LLNYYLQLDIF,KNQTRPESNR...",35.0,0.0,False,ns,ns,ns,ns,ns
909,ENSG00000041880__TCONS_00610801__ncRNA__3__CTG,NaN,NaN,NaN,NaN,NaN,NaN,LCFTPLVAK,LCFTPLVAK,ENSG00000041880__TCONS_00610801__ncRNA__3__CTG,...,NaN,NaN,NaN,0.0,False,not expressed,ns,ns,downregulated,ns
910,ENSG00000278834__ENST00000619697__ncRNA__1__TTG,NaN,NaN,NaN,NaN,NaN,NaN,VLYEGLESK,VLYEGLESK,ENSG00000278834__ENST00000619697__ncRNA__1__TTG,...,NaN,NaN,NaN,1.0,True,not expressed,ns,ns,ns,ns

In [24]:
'a' in 'abc'

True

In [10]:
df_merge['detected_in_hla_la'] = False
df_merge['hla_la_peptide'] = None
for index, row in hlala.iterrows():
    for index2, row2 in df_merge.iterrows():
        if row['Sequence'] in row2['Protein']:
            df_merge.at[index2, 'detected_in_hla_la'] = True
            df_merge.at[index2, 'hla_la_peptide'] = row['Sequence']
            print(f"Match found: {row['Sequence']} in {row2['orf_id']}: {row2['Protein']}")

Match found: AAATAVAMR in ENST00000428135_12_167: MAARPSRATGPRGGQRSRVKPPPGRRLKEQLPPLAAARAVFAAATAVAMRRG
Match found: VAAEVAGAGR in ENST00000393972_103_192: MGRAGTMAVAAEVAGAGRLAVEEAVVLRGL
Match found: MAASGAGAEVSGR in ENSG00000143570_ENSG00000143545__ENST00000471173__ncRNA__6__ATG: MAASGAGAEVSGR
Match found: ETSQLSQIGR in ENSG00000168575_ENSG00000254165__ENST00000518384__uORF__8__ATG: MCQMPEETSQLSQIGRKNMECVLPLTEHNQMNCPDSSLQTSS
Match found: ETSQLSQIGR in ENST00000517366_1_168: MMQISVFLPAAWLQLILAGEETSQLSQIGRKNMECVLPLTEHNQMNCPDSSLQTSS
Match found: DSAPSAQALTR in ENSG00000204956_ENSG00000240184__ENST00000308177__uORF__25__ATG: MSDSAPSAQALTR
Match found: ETVASAATVGAAR in ENST00000282570_80_136: METVASAATVGAAREKVAV
Match found: AAAAFVVPR in ENSG00000102531__ENST00000492622__uORF__3__ATG: MAAAAFVVPRVKQKAGATRRGSEERG
Match found: IWDLSITRL in TCONS_00673441_793_924: MPLLRPVSSHEPQHKTDGPVLTVDNFPCLSKRWDSIWDLSITRL
Match found: ASAAVRVAY in TCONS_00635532_60_152: MLTAPGDRRAGEPCSVAPRSASAAVRVAYRS
Match found: AVFAAATAVAMR in ENST00000428135_12_167: MAARPSRATGPRGGQRSRVKPPPGRRLKEQLPPLAAARAVFAAATAVAMRRG
Match found: FSGSMVVLR in TCONS_00693051_798_833: MLQFSGSMVVLR
Match found: SAVSTRVYK in ENSG00000087152__ENST00000587097__uoORF__12__ATG: MSSQSAVSTRVYK
Match found: ETGGVGDVSR in TCONS_00137184_5_91: MVAETGGVGDVSRGRVASVGTLGAEQLPH
Match found: EAVGVMATR in ENSG00000144747_ENSG00000265355__ENST00000646708__uORF__5__ATG: MGPLRLSCAGTAEGNIPGSREAVGVMATR
Match found: SVKTLDGPTFR in TCONS_00462910_224_286: MIHQPLVLPSVKTLDGPTFRS
Match found: SVKTLDGPTFR in TCONS_00462910_224_286: MIHQPLVLPSVKTLDGPTFRS
Match found: MAVGGTAVITR in ENST00000441076_4_99: MAVGGTAVITRRLLGRSGFSFQVTIRKAKFAV
Match found: FTSSYLSRR in ENSG00000091986__ENST00000206423__uORF__5__ATG: MEIQRLRRTAPFTSSYLSRR
Match found: MIFSGVFLR in ENSG00000221914__ENST00000520329__uoORF__8__ATC: MRRHPPSLPPHPQVRGVSSGSGDPEEPSRVTICSATWQELEEGMIFSGVFLR
Match found: ARFYNPPGTPK in ENST00000261947_113_172: MEGARFYNPPGTPKRRPRAT
Match found: SLLPLRVLL in ENSG00000131165__ENST00000675536__uoORF__6__TTG: MASLLPLRVLLLSLWPWTIPCSS
Match found: AERPPGVAA in ENSG00000148498_ENSG00000215184__ENST00000545693__uORF__8__ATG: MRAERPPGVAAACPRP
Match found: MEARPPPPP in ENST00000455631_192_251: MEARPPPPPRGSEPRAGRRP
Match found: MEARPPPPP in ENSG00000215305_ENSG00000132670__ENST00000216877__uORF__7__ATC: MTVARPVAPQPLPLAMEARPPPPPRGSEPRAGRRP
Match found: SEVQSTVEA in ENSG00000155096__ENST00000347770__uORF__9__ACG: MLSHLGNLADDRGVPSPNLSMEVFTSEIQDSYSSSLVSSGLLLPELSCDYLRDVSVSSEVQSTVEAFVAVCCIF
Match found: MVAESPPRV in ENSG00000235106__ENST00000432807__uORF__5__ATC: MSSSSVVQAMVAESPPRV
Match found: AEIMGKLLA in ENSG00000138674_ENSG00000251022__TCONS_00658672__ncRNA__12__ATT: MLAQSGAIVLLVRPSLKMRSREAGPKLRRIQEPANGSPGAVSETGGYREERLSDAEIMGKLLAWLAVGM
Match found: MTMSTILSKK in ENST00000664641_241_333: MDIVSIVGAEKLEAMTMSTILSKKKQCLRNI
Match found: MTMSTILSKK in ENSG00000247516_ENSG00000284000__ENST00000664641__ncRNA__2__AAG: MTSMAPMDIVSIVGAEKLEAMTMSTILSKKKQCLRNI
Match found: ESDVSSALSY in ENST00000651170_461_1213: MKMLQARKQHMSTELTIESEAPSDSSGINLSGFGSEQLDTNDESDVSSALSYILPYLSLRNLGDQLEIQLTEQLRSLIPNEDVRKFMSHVIWTLKMECSETHVQGSCAKLMSRTGLLMKLLSEQQEAKALNVEWDTDQQKTNYINENMEQNEQKEQKSSELMKEVPGYDYKNKLIFAISVTVILIILIIIFCFIEVKTIINSGFQNTILCLCGFRIHKLKTNVTFPLDILLLSFKAEVCFVLLLQCIFQDC
Match found: ASFFTTGSSSK in ENST00000623210_17346_17483: MAVVRNSSHSAAVAGKALHGVTGQSLSWKRAGRKSASFFTTGSSSK
Match found: ASFFTTGSSSK in ENSG00000139722__ENST00000543590__ncRNA__3__CTG: MFTSASTMAVVRNSSHSAAVAGKALHGVTGQSLSWKRAGRKSASFFTTGSSSK
Match found: APAAGRRGQL in ENST00000610387_101_178: MSAPAAGRRGQLGISRSLWGGGHSDV
Match found: APAAGRRGQL in ENST00000610387_101_178: MSAPAAGRRGQLGISRSLWGGGHSDV
Match found: SVYAGGRGPAK in ENST00000296473_396_494: MSVYAGGRGPAKLCPQAGPGRTPLPLHGSGRGQ
Match found: GEGKASPGV in ENSG00000156858__ENST00000565410__ncRNA__9__GTG: MDPWGSTLSSEMLQLGPPLSERSFAALKLTGEGKASPGV
Match found: GEGKASPGV in ENST00000569864_62_145: MLQLGPPLSERSFAALKLTGEGKASPGV
Match found: YAGGRGPAK in ENST00000296473_396_494: MSVYAGGRGPAKLCPQAGPGRTPLPLHGSGRGQ
Match found: SISVPLSMK in ENST00000661090_71_127: MAASISVPLSMKFIYLNKI
Match found: AVTRTTPVK in ENST00000395472_184_303: MAMVMAAVTRTTPVKLRSGRYIQKVPRRNFLLEKMKKQYL
Match found: FSFQVTIRK in ENST00000441076_4_99: MAVGGTAVITRRLLGRSGFSFQVTIRKAKFAV
Match found: FSFQVTIRK in ENST00000441076_4_99: MAVGGTAVITRRLLGRSGFSFQVTIRKAKFAV
Match found: QEAHPGTSI in ENST00000432401_168_311: MAGPELLLDSNICLWVVLPIVITLRRHDPPLRVHPAGERQEAHPGTSI
Match found: RVWKHLTTK in ENST00000548983_279_452: MLSRVWKHLTTKCYPCENSYSTRGSASVFSYSATDINTSVCNTVHPLPHLPDPLQEAC
Match found: EVYHTTVLK in ENSG00000168036__ENST00000349496__uoORF__8__TTG: MARPRERRARGGGDGGRSEEQLQSPPSRHRRSRTVGLPRREEPVPLRVFEVYHTTVLKIQRGQWLLKLI
Match found: RLAPCPPLQR in ENSG00000174282__ENST00000380599__uoORF__4__ACG: MRRHRSQKEEAQQKGLAEPPPAPLHVGCALRLAPCPPLQR
Match found: RLAPCPPLQR in ENSG00000174282__ENST00000380599__uoORF__4__ACG: MRRHRSQKEEAQQKGLAEPPPAPLHVGCALRLAPCPPLQR
Match found: MLLLRPTIFK in ENST00000397601_487_549: MTLSMLLLRPTIFKWDILIDE
Match found: KLRLGEVTK in ENSG00000133961_ENSG00000284930__ENST00000555859__uORF__7__CTG: MLQFKILIYIHRLEYWWASNPQTPHLGQMRKLRLGEVTKLVQNHTTCKGHSQDSEPGCKN
Match found: ALLGVRGVGK in ENSG00000261408_ENSG00000250506__ENST00000586891__uORF__1__ATG: MSASWLGPVAGQTNPLLLARGGSRADPRERGSEGQETALLGVRGVGK
Match found: ALLGVRGVGK in ENST00000567351_51_191: MSASWLGPVAGQTNPLLLARGGSRADPRERGSEGQETALLGVRGVGK
Match found: FGYSRHTPF in ENSG00000175215__ENST00000547169__ncRNA__14__CTG: MSCVGMKTIEDSIAKPWPFLSVVRPMPRIKEGYAFGYSRHTPF
Match found: RLVTEPSGPK in TCONS_00286528_45433_45483: MRLVTEPSGPKARPRCR
Match found: RLLSKNSLLLK in ENSG00000163872__ENST00000305135__iORF__2__CTG: MESSEPSKKPTLITRMYLWPFQISGIKQLRIQLEMLLCRRLRLLSKNSLLLK
Match found: VPRVAAAAL in ENSG00000134046_ENSG00000207233__ENST00000583046__iORF__2__GTG: MAGGGGSRRAGAAASVAVAGAGAVAGDGDGAGAGAAAVPRVAAAALAATAAAAAAAAAVAAAPPGGSRSLSRRGARGRGPGDPGPRRAGRGWIARPSPPDGRRRK
Match found: KLTYIYIQK in TCONS_00602688_214_264: MDASKLTYIYIQKCFAT
Match found: RISHWTATK in ENST00000560205_105_215: MEEAVRTASAPNARISHWTATKAVAVRAQDWAACVGV
Match found: VTYHMFRTK in ENST00000453465_41_148: MLSGNLIKKELCLYYSSSRKVTYHMFRTKVHFYVEL
Match found: VTYHMFRTK in ENST00000453465_41_148: MLSGNLIKKELCLYYSSSRKVTYHMFRTKVHFYVEL
Match found: RMMPLAGLVK in ENSG00000204237__ENST00000575992__dORF__7__ATG: MERMMPLAGLVK
Match found: RFYNPPGTPK in ENST00000261947_113_172: MEGARFYNPPGTPKRRPRAT
Match found: ALSPVLLPR in ENST00000510527_84_161: MRTARESRALSPVLLPRAAVALRPLE
Match found: RLAGLGALK in ENSG00000162104__ENST00000294016__uORF__3__ATG: MEGSAPPAELFVRRRLAGLGALKV
Match found: SLSGSLSAK in ENSG00000181038_ENSG00000092931__ENST00000590964__uoORF__9__TTG: MLRAFFARSAAGLSPDLGFPLLAVRCYGHVARGFPLAQSGSPEPSAVPRPPGAQRRPTGRARFPRTGGPGPALSILGGAGSGGRRGCPGGPRPADWSWSEPSRNFGCQMWCRSNTVRQLRTASLSGSLSAKLPNE
Match found: SLYLSYRPK in ENSG00000185009__ENST00000355264__iORF__2__ATG: MYHLSFQHLTTTSSVSTGISSSLYLSYRPKCHLSL
Match found: QPAGGHVAA in ENST00000375635_41_193: MRVVMARLLSEGEQGIPTACAAFAQQPAGGHVAAWLGSCKTFIAVLSLSKE
Match found: QPAGGHVAA in ENST00000375640_341_451: MRVVMARLLSEGEQGIPTACAAFAQQPAGGHVAAWLG
Match found: RVSGTSSIYK in ENSG00000105429__ENST00000251268__uORF__5__ATG: MEPCVYRGLLRSLGFGPVHNDSIYRAFHRSIGLSPRLPEPVSSGRTLRRDCRVSGTSSIYKVMLCL
Match found: DGYLRASEL in ENST00000576606_20_244: MSAPAQSKELETYQAGGLCCASLAHIFPKHSQEPGNSVPLWPSLEHHICTLQSVDQLRDGYLRASELSLPPSIIS
Match found: GVYTGKLSEK in TCONS_00065499_113_202: MAGNEPDEGSQAGVYTGKLSEKSSLGCLEI
Match found: RVSVVAEPK in ENSG00000100908__ENST00000560403__uORF__6__ATG: MQSGPPPGLGRGRTPGPRAPGAGGLPASRVSVVAEPK
Match found: SVSAVLGARR in ENSG00000204070_ENSG00000244274__ENST00000243918__uORF__8__ATG: MVLSVSAVLGARR
Match found: ETSQESFWLR in ENSG00000100532__ENST00000216420__iORF__4__ATT: MGMVWLGCSSNSEKFRRDPVQHKSFQKANETSQESFWLRDH
Match found: ELIALTQALR in ENST00000666458_493_840: MWVPTKIPPLSPQLLTPGSGKVDATVFTDSSSFLEKGLRKAGAAVTMETDVLWAQALPANTSAQKAELIALTQALRWGKDINVNTDSRYAFATVHVRGAIYQERGLLTSAGGCNPL
Match found: RSASAAVRVAY in TCONS_00635532_60_152: MLTAPGDRRAGEPCSVAPRSASAAVRVAYRS
Match found: FTVALWRQR in ENSG00000078747_ENSG00000125971__ENST00000664852__uORF__7__ATG: MHFTVALWRQRLNPRK
Match found: DTLLLGSPR in ENST00000318041_37_66: MDTLLLGSPR
Match found: DTITLIGPR in ENST00000614443_97_288: MRVKRQLPTFWGRSAEARFPGPSGDTRTGGLSVEVAAAESCASAAECCARPADTITLIGPRREV
Match found: ELGPAFALR in ENSG00000197563__ENST00000639214__ncRNA__13__ATC: MASVGRGDHCPRALMELGPAFALRSPRFRDQA
Match found: ELGPAFALR in ENST00000640252_141_194: MELGPAFALRSPRFRDQA
Match found: EVVTEVVSR in ENST00000395797_138_269: MEESYEEVVTEVVSRSGHVWISNSYPAGLSWKICPECSVLQCDD
Match found: EVVTEVVSR in ENSG00000169740__ENST00000374433__uoORF__1__ACG: MRRCGAQEQPMEESYEEVVTEVVSRSGHVWISNSYPAGLSWKICPECSVLQCDD
Match found: FAALTSAPR in ENST00000576143_129_209: MSGVFAALTSAPRVRDGTHQPPSRRRR
Match found: DSANIICPR in ENST00000579147_3_128: MPAVSAEERRWRLTDQSRWSWRRGRQAADSANIICPRLKNSR
Match found: DSANIICPR in ENSG00000087191__ENST00000310144__uoORF__6__ATG: MPAVSAEERRWRLTDQSRWSWRRGRQAADSANIICPRLKNSS
Match found: DAAPTVTSTR in ENSG00000155111__TCONS_00718555__ncRNA__5__GTG: MEEVAAVAAEESLAEGGPRSGGRRAARARAREAAVGEVERRSRGEEEEGLSGGGPRVPCLYGGSRQWIMISRRSWRRSGSGWRICLSTKGAKWDAAPTVTSTRRGGKMDSRRASCMDLKRWR
Match found: DAAPTVTSTR in ENSG00000155111__ENST00000368911__uoORF__3__GTG: MEEVAAVAAEESLAEGGPRSGGRRAARARAREAAVGEVERRSRGEEEEGLSGGGPRVPCLYGGSRQWIMISRRSWRRSGSGWRICLSTKGAKWDAAPTVTSTRRGGKMEKMKRNMH
Match found: RMSTAVYRW in ENSG00000102974__ENST00000642819__iORF__4__GTG: MMQSKPLWRSPKLLLKERRERLTRDAGKGARKKMPATYPRTRRMGVRWSRMSTAVYRW
Match found: WAASASIPR in ENSG00000088826__ENST00000484515__ncRNA__3__AAG: MRQPMGNAAWAASASIPRMAWPATLPTTAAGSPRTWLRNSAIYTTRSIT
Match found: ELPSSLSFPR in ENST00000302345_179_295: MELPSSLSFPRCQLGQGRWSNFAVERLHVLPNESKQRYC
Match found: ELPSSLSFPR in TCONS_00348255_335_454: MELPSSLSFPRCQLGQGRWSNFAVERLHVLPNESPACLSR
Match found: SARGGGVAY in ENSG00000079999__ENST00000393623__uoORF__2__ATG: MAGSLSARGGGVAYLLEPHAARSQA
Match found: SARGGGVAY in ENST00000393623_103_267: MVTCARSAPPPRAAMEAPGLGRWRRSRSAAMAGSLSARGGGVAYLLEPHAARSQA
Match found: VQYHGQHRV in ENSG00000029364__ENST00000336643__uORF__8__AGG: MPGRVQYHGQHRV
Match found: RSREAGPKL in ENSG00000138674_ENSG00000251022__TCONS_00658672__ncRNA__12__ATT: MLAQSGAIVLLVRPSLKMRSREAGPKLRRIQEPANGSPGAVSETGGYREERLSDAEIMGKLLAWLAVGM
Match found: RTWGSSSPK in ENST00000442581_259_537: MGGHVPLQRTWGSSSPKRGTGTEKGGPHLPAPSASPIPGPPPHWSLKGPACLGAEPAEALSRAAPGRTAGAGWAGPGMAVALAPVPVAPRASS
Match found: TELRSVSTI in ENSG00000103540__ENST00000565376__uORF__2__ATG: MAGRRRRRRRRTELRSVSTI
Match found: KELVRFLNL in ENSG00000167264_ENSG00000263276__ENST00000562926__orphan__16__ATC: MMDYRLTLLFCHHRFSSKVTKTMKELVRFLNLNIAH
Match found: KEVFLAQPV in ENST00000376033_229_312: MSFQRNVRSLGADCQGKGWKEVFLAQPV
Match found: AEYPELRGVF in ENST00000409011_460_540: MLVSGGLRSTILPQSMVAEYPELRGVF
Match found: MTMSTILSK in ENST00000664641_241_333: MDIVSIVGAEKLEAMTMSTILSKKKQCLRNI
Match found: MTMSTILSK in ENSG00000247516_ENSG00000284000__ENST00000664641__ncRNA__2__AAG: MTSMAPMDIVSIVGAEKLEAMTMSTILSKKKQCLRNI
Match found: SAAQVFMNK in ENSG00000171408__ENST00000308191__uoORF__3__ATG: MKLLDSAAQVFMNKQHRSEISRHSKVTELPLWLNVLFNG
Match found: QVMSLGLQK in ENSG00000141076_ENSG00000132612__ENST00000563094__iORF__9__ATA: MTCQQTTFRRNFSQVMSLGLQKLCAGQKDSDSLVLGSMARLWSMIYRR
Match found: VTGQSLSWK in ENST00000623210_17346_17483: MAVVRNSSHSAAVAGKALHGVTGQSLSWKRAGRKSASFFTTGSSSK
Match found: VTGQSLSWK in ENSG00000139722__ENST00000543590__ncRNA__3__CTG: MFTSASTMAVVRNSSHSAAVAGKALHGVTGQSLSWKRAGRKSASFFTTGSSSK
Match found: AVSGVALAR in ENST00000512970_131_232: MPEGAVSGVALARRGWSVRGHTGKPSGVGRQCRC
Match found: STYNPSISLK in ENSG00000152601__ENST00000485910__uORF__10__ATT: MRCRRVCHVFMLAFWAPNWHWEGVTESTRLIPGPTFKRSSTYNPSISLKTKTSLN
Match found: RSMSPLTKVQK in ENST00000664637_173_271: MAAFARSAITASLRGLQGVRSMSPLTKVQKLAS
Match found: SLSRPLIGK in ENSG00000136305__ENST00000258807__uORF__4__ATG: MPSKDIPAPFTSLSRPLIGKRRKVREDDLSVTAAGSSGK
Match found: TSLSRPLIGK in ENSG00000136305__ENST00000258807__uORF__4__ATG: MPSKDIPAPFTSLSRPLIGKRRKVREDDLSVTAAGSSGK
Match found: LLTLSSQSY in ENSG00000080603_ENSG00000156873__ENST00000411466__uoORF__2__GTG: MIPFSTAAPWKCRLSQGVWSQLTQVLQRLVDLSGGWDALVGPGPWKAGPGGRWPRMRPAPSMPCSRTPAPRPAVLVITTQSFFRHPRGSLGVGPCRAAPPLLTLSSQSYRHRWCRTA
Match found: LLTLSSQSY in ENST00000411466_421_606: MRPAPSMPCSRTPAPRPAVLVITTQSFFRHPRGSLGVGPCRAAPPLLTLSSQSYRHRWCRTA
Match found: AAAKTLNPK in ENST00000442266_1_210: MAAAKTLNPKAKVAGAQAALAFNISGARGLQDVLRTNLGPKGTIKILVSGAGDIKLTKDTGVDDQPWPTW
Match found: ASLSGSLSAK in ENSG00000181038_ENSG00000092931__ENST00000590964__uoORF__9__TTG: MLRAFFARSAAGLSPDLGFPLLAVRCYGHVARGFPLAQSGSPEPSAVPRPPGAQRRPTGRARFPRTGGPGPALSILGGAGSGGRRGCPGGPRPADWSWSEPSRNFGCQMWCRSNTVRQLRTASLSGSLSAKLPNE
Match found: AVMGPAQVVGMK in ENSG00000213762__ENST00000597975__ncRNA__6__GTG: MMAAAAVMGPAQVVGMK
Match found: AVMGPAQVVGMK in ENSG00000213762__ENST00000597975__ncRNA__6__GTG: MMAAAAVMGPAQVVGMK
Match found: TVNNVYINK in ENST00000483450_176_241: MEPKSLDFSEGRTTVNNVYINK
Match found: TVNNVYINK in ENSG00000197935__TCONS_00734127__ncRNA__1__GTG: MNKTTKIPALMEPKSLDFSEGRTTVNNVYINK
Match found: ATFFGIQLLK in ENST00000562439_138_251: MLGISSATFFGIQLLKTNRMQIPQLQVMKTVLGKLKTT
Match found: MLFSQIFFK in ENSG00000128159__ENST00000439308__iORF__10__ATG: MLFSQIFFKMRLNSCSLTCQNYQRETRSSCCPLT
Match found: SVFQSTWIK in ENSG00000256087_ENSG00000197608__TCONS_00440178__ncRNA__5__ATG: MSVFQSTWIKRLLLFVYLD
Match found: SVFQSTWIK in ENST00000598446_15_71: MSVFQSTWIKRLLLFVYLD
Match found: RVAASVQRL in ENST00000228437_130_339: MRNKAVGQARAPPAQLAGWAAPFPKLLDGRPQVFPEMPQPVAGCTATGPREKLGGPGRPRGRVAASVQRL
Match found: STFSSLVAK in ENSG00000023191__ENST00000354420__uoORF__8__ACG: MFNPFCWLENEVGRLALGLQARDRPPVVPRHEELLTDRNGGCVQSFEDGRAALQNPSSQPRPVRLSYNKSSSTCSTFSSLVAKRGVSESPACETVRGFGQDVLFPLPPTQATLHLHHEPGHPEPGHPV
Match found: MTLMVFLFK in ENSG00000033170__ENST00000549235__ncRNA__5__CTG: MHRGRREFSESERVAAFAQRTSMTLMVFLFKIK
Match found: ATIGSGNLQR in TCONS_00479309_117_200: MCVRAKERKNGSAQTHRPATIGSGNLQR
Match found: ATIGSGNLQR in TCONS_00479309_117_200: MCVRAKERKNGSAQTHRPATIGSGNLQR
Match found: TPAPRPAVL in ENSG00000080603_ENSG00000156873__ENST00000411466__uoORF__2__GTG: MIPFSTAAPWKCRLSQGVWSQLTQVLQRLVDLSGGWDALVGPGPWKAGPGGRWPRMRPAPSMPCSRTPAPRPAVLVITTQSFFRHPRGSLGVGPCRAAPPLLTLSSQSYRHRWCRTA
Match found: TPAPRPAVL in ENST00000411466_421_606: MRPAPSMPCSRTPAPRPAVLVITTQSFFRHPRGSLGVGPCRAAPPLLTLSSQSYRHRWCRTA
Match found: RAAAGRPPL in ENSG00000101752_ENSG00000199977__ENST00000261537__uORF__5__CTG: MERRLGISFLLLSSRDRAALWKPSHSIIAEDPPPRHSEKVPLRPWVRRYPDVESLSPGWDSVAGRSAAAGAGAERRGPEGPGARRTPGGTTAAHGGGGGAGAWVPAPERGAGVAERPAVKLAPRRPPRASLPRPPALLALPAGGERGFLAAVAVAWPGSPEEAGESPPTAPSPLPALRRRLRAAAGRPPLRAGGAAATAGQRLWAPRGPRRRPRELFSRPPGLAAAPADA
Match found: ALISVVTTA in ENSG00000121579_ENSG00000239280__ENST00000493900__uoORF__4__ACG: MTALISVVTTASAGGEDERPDRAGRCDTTQY
Match found: SSSPVIFHV in ENSG00000205323_ENSG00000135392__ENST00000546957__iORF__6__ATT: MGWTQAMAPQGVQDHLEMQRTLIRVRRLQKKNQEWTRNSQKKTRLGTRRMGTLFFPFHLLATAREHLEFQKGLTLREEMVLLATFATTVPLQLWGKMSWKRNMMMKNLSSSPVIFHVCPAERNPHPGDSGTAFQRRRILGRVDVGIPGPLVDIGWVGNEVRQISAKAWDCGEPRNYVNLDRQAFGG
Match found: FLFSDPATASL in ENSG00000135211__ENST00000257663__uoORF__1__ATG: MGGKGRKRTRIQTGEFADLRVPLRFPAGSAARVYFLFSDPATASLNCLNENVLGSESTTHLAFHTTLLDHVGVETG
Match found: HRFSSKVTK in ENSG00000167264_ENSG00000263276__ENST00000562926__orphan__16__ATC: MMDYRLTLLFCHHRFSSKVTKTMKELVRFLNLNIAH
Match found: FLYSPDILI in ENST00000429705_49_192: MISAGCGVSAAGRELSAPRPLRTDARLPAEISMTTLKMNFLYSPDILI
Match found: EIIRQLNGV in ENST00000347613_476_562: MQNPKAAQKTATDFAMSLSCEIIRQLNGV
Match found: EIIRQLNGV in ENST00000347613_476_562: MQNPKAAQKTATDFAMSLSCEIIRQLNGV
Match found: VRVGVRGPL in ENSG00000135446__ENST00000551706__ncRNA__8__ATG: MVRVGVRGPL
Match found: AEEPLAGRTW in ENSG00000175482_ENSG00000175505__ENST00000531239__dORF__5__GTG: MQSLASLSPMRHHVRPPALSSLAHHPRTSGQKREPIAPAQLSPAAEEPLAGRTWRCQRLNSSI
Match found: SLISTYFHV in ENSG00000115355__TCONS_00492358__ncRNA__18__TTG: MTGFLSWVPAPFPFLLLQMPFLCPSSPGTDISSAGCCSWCPSSKPLLGISARFTLGCFLRRESAPLLHDGIFLPCRNGLSLISTYFHV
Match found: EEPISLHTW in ENSG00000164961__ENST00000521109__ncRNA__4__CTG: MRIEEDRRLEGGVETGCRLRARPPALRVRRGAARLTGSLMEEPISLHTWFHLIIYRHQL
Match found: EEYRGGNNW in ENSG00000198677__ENST00000649566__uORF__5__ATG: MGKEQSNSIREEYRGGNNW
Match found: EEAAAAKGGVW in ENST00000540224_96_170: MEGEEEAAAAKGGVWGRLQGPLCHS
Match found: SLWRAGGTLTL in ENSG00000169851__ENST00000361762__uORF__5__AAG: MMARASLWRAGGTLTLTAL
Match found: ASAQLTILH in ENSG00000244300__ENST00000464242__ncRNA__2__CTG: MASVCLSEASAQLTILHQLVK
Match found: ASAQLTILH in ENSG00000244300__ENST00000464242__ncRNA__2__CTG: MASVCLSEASAQLTILHQLVK
Match found: YSSSRKVTY in ENST00000453465_41_148: MLSGNLIKKELCLYYSSSRKVTYHMFRTKVHFYVEL
Match found: AERPPGVAAA in ENSG00000148498_ENSG00000215184__ENST00000545693__uORF__8__ATG: MRAERPPGVAAACPRP
Match found: AEVAGAGRLA in ENST00000393972_103_192: MGRAGTMAVAAEVAGAGRLAVEEAVVLRGL
Match found: AEQALLARA in ENST00000340099_131_223: MSLLRGAAEQALLARASAPSRRGAKELLEQC
Match found: RTAPFTSSY in ENSG00000091986__ENST00000206423__uORF__5__ATG: MEIQRLRRTAPFTSSYLSRR
Match found: APGSDRLLGL in ENST00000580238_63_107: MAAPGSDRLLGLRRE
Match found: YLYWGNIAYK in ENST00000559249_260_550: MSLFDENELLRSHWYLYWGNIAYKQEAYSLSGENFFMSETENSCSRLCHPFFSRQKIPKSCNQRSLHLIDKATNKPKCLSMSTAACQTSSIATRCPV
Match found: MFFTRMQSF in ENST00000372714_45_284: MSDSCQRQQQGDTKWRRLSSYPWRRRQRWRRRRHLLQAAAAVSQAAAAPPAGAVAVARSQVLISQLKMFFTRMQSFLLVK
Match found: EEEAAAAKGGVW in ENST00000540224_96_170: MEGEEEAAAAKGGVWGRLQGPLCHS
Match found: EEAVVLRGL in ENST00000393972_103_192: MGRAGTMAVAAEVAGAGRLAVEEAVVLRGL
Match found: MEINHFSSGF in ENSG00000167920__TCONS_00360682__ncRNA__1__ATG: MELTPIMEINHFSSGF
Match found: MEINHFSSGF in ENST00000668620_316_375: MLPAMELTPIMEINHFSSGF
Match found: MEEPISLHTW in ENSG00000164961__ENST00000521109__ncRNA__4__CTG: MRIEEDRRLEGGVETGCRLRARPPALRVRRGAARLTGSLMEEPISLHTWFHLIIYRHQL
Match found: AEIMGKLLAW in ENSG00000138674_ENSG00000251022__TCONS_00658672__ncRNA__12__ATT: MLAQSGAIVLLVRPSLKMRSREAGPKLRRIQEPANGSPGAVSETGGYREERLSDAEIMGKLLAWLAVGM
Match found: YLYWGNIAY in ENST00000559249_260_550: MSLFDENELLRSHWYLYWGNIAYKQEAYSLSGENFFMSETENSCSRLCHPFFSRQKIPKSCNQRSLHLIDKATNKPKCLSMSTAACQTSSIATRCPV
Match found: KEQLPPLAAA in ENST00000428135_12_167: MAARPSRATGPRGGQRSRVKPPPGRRLKEQLPPLAAARAVFAAATAVAMRRG
Match found: GEFADLRVP in ENSG00000135211__ENST00000257663__uoORF__1__ATG: MGGKGRKRTRIQTGEFADLRVPLRFPAGSAARVYFLFSDPATASLNCLNENVLGSESTTHLAFHTTLLDHVGVETG
Match found: GELQGTQAP in ENSG00000143612__ENST00000640799__uORF__7__ATG: MAGELQGTQAPSLRRSLG
Match found: KEQLPPLAA in ENST00000428135_12_167: MAARPSRATGPRGGQRSRVKPPPGRRLKEQLPPLAAARAVFAAATAVAMRRG
Match found: MEVASVAAY in TCONS_00073836_176_328: MEVASVAAYCAGCSSLCSAARCRIRCPLWLFCWLEDRPGAATPPLGKAETL
Match found: EIMGKLLAW in ENSG00000138674_ENSG00000251022__TCONS_00658672__ncRNA__12__ATT: MLAQSGAIVLLVRPSLKMRSREAGPKLRRIQEPANGSPGAVSETGGYREERLSDAEIMGKLLAWLAVGM
Match found: VLVITTQSF in ENSG00000080603_ENSG00000156873__ENST00000411466__uoORF__2__GTG: MIPFSTAAPWKCRLSQGVWSQLTQVLQRLVDLSGGWDALVGPGPWKAGPGGRWPRMRPAPSMPCSRTPAPRPAVLVITTQSFFRHPRGSLGVGPCRAAPPLLTLSSQSYRHRWCRTA
Match found: VLVITTQSF in ENST00000411466_421_606: MRPAPSMPCSRTPAPRPAVLVITTQSFFRHPRGSLGVGPCRAAPPLLTLSSQSYRHRWCRTA
Match found: TELKSFPREW in ENSG00000100554__ENST00000216442__uoORF__6__CTG: MTPVEEDTVEASSGAIAASVARPGTRAEKLSSECRAKTELKSFPREWHRPS
Match found: TELKSFPREW in ENSG00000100554__ENST00000216442__uoORF__6__CTG: MTPVEEDTVEASSGAIAASVARPGTRAEKLSSECRAKTELKSFPREWHRPS
Match found: KLIDYGLSGY in ENSG00000109016__ENST00000395511__uoORF__3__AGG: MMKLIDYGLSGYQEESAEGEGHGLHHLHSHPAPAVRLPGRLRPLPAAAVGAREGLPAECCGGDHRRHLRAGQRMCKSLLCCGC
Match found: RTAIIVGGK in ENSG00000039650_ENSG00000204673__TCONS_00414294__ncRNA__33__ATT: MEHMRTAIIVGGKWKCSRRGHFS

In [11]:
df_merge['detected_in_hla_la'].value_counts()

detected_in_hla_la
False    762
True     149
Name: count, dtype: int64

In [12]:
df_merge[df_merge['detected_in_hla_la']]['orf_category_new'].value_counts()

orf_category_new
uORF              79
uoORF             32
intORF            18
lncRNA ORF        15
pseudogene ORF     3
doORF              1
dORF               1
Name: count, dtype: int64

In [13]:
df_merge['result_A673'].value_counts()

result_A673
ns               467
not expressed    430
downregulated      9
upregulated        5
Name: count, dtype: int64

In [14]:
df_merge.columns

Index(['protein', '1_peptides', '1_peptides_no_match_sp', '2_peptides',
       '2_peptides_no_match_sp', '3_peptides_proteotypic',
       '3_peptides_not_proteotypic', '4_peptides', '4_peptides_no_match_sp',
       'orf_id', 'ORF_ranges', 'Protein', 'gene_id', 'gene_biotype',
       'gene_name', 'transcript_id', 'uniprot_gn_ids', 'cl_mean', 'ps_mean',
       'ps_n_translated', 'ps_translated', 'translated_A673',
       'translated_SKNMC', 'translated_MHHES1', 'translated_RDES',
       'translated_TC106', 'EwS_specific', 'orf_category_new',
       'same_as_orfquant', 'same_as_orfquant_start', 'neotranscript_orf_type',
       'neotranscript_type', 'isoform_final', 'distance_chip', 'distance_msat',
       'peak_orth_near', 'ggaa_near', 'Peptides_SB', 'Number_SB',
       'Peptides_WB', 'Number_WB', 'class', 'any_peptide_found_in_IP',
       'result_A673', 'result_SKNMC', 'result_MHHES', 'result_TC106',
       'result_RDES', 'detected_in_hla_la', 'hla_la_peptide'],
      dtype='str')

In [15]:
cols = [
    'result_A673', 'result_SKNMC', 'result_MHHES',
    'result_TC106', 'result_RDES'
]

df_merge['n_downregulated'] = df_merge[cols].eq('downregulated').sum(axis=1).astype(int)
df_merge['n_downregulated'].value_counts()

n_downregulated
0    647
1    157
2     66
3     21
4     18
5      2
Name: count, dtype: int64

In [16]:
df_merge[df_merge['n_downregulated'] >= 3]['detected_in_hla_la'].value_counts()

detected_in_hla_la
False    39
True      2
Name: count, dtype: int64

In [17]:
df_merge[df_merge['n_downregulated'] >= 3]['4_peptides'].notna().value_counts()

4_peptides
True     29
False    12
Name: count, dtype: int64

In [18]:
df_merge['neotranscript_orf_type'].value_counts()

neotranscript_orf_type
Non-canonical ORF general    882
In-frame ORF                  15
Neogene ORF                   13
Out-of-frame ORF               1
Name: count, dtype: int64

In [19]:
df_merge['type_of_fusion_regulation'] = df_merge['n_downregulated'].apply(lambda x: 'EF1 controlled' if x >= 3 else 'Not EF1 controlled')
df_merge['type'] = df_merge['neotranscript_orf_type'].where((df_merge['neotranscript_orf_type'] == 'Neogene ORF')|(df_merge['neotranscript_orf_type'] == 'Out-of-frame ORF')|(df_merge['neotranscript_orf_type'] == 'In-frame ORF'), df_merge['type_of_fusion_regulation'])
df_merge['type'].value_counts()

type
Not EF1 controlled    849
EF1 controlled         33
In-frame ORF           15
Neogene ORF            13
Out-of-frame ORF        1
Name: count, dtype: int64

In [20]:
df_merge.to_csv('proteomics_detected_orfs_with_extra_features.csv', index=False)