In [44]:
import pandas as pd

In [45]:
df = pd.read_csv("peptides_by_protein.tsv", sep="\t")
df

,protein,1_peptides,1_peptides_no_match_sp,2_peptides,2_peptides_no_match_sp,4_peptides,4_peptides_no_match_sp
0,ENST00000291041_23_121,NaN,NaN,NaN,NaN,AAAAAAAAIAR,AAAAAAAAIAR
1,ENST00000303204_18_68,NaN,NaN,NaN,NaN,AAAAAAAAWAR;AAAAAAAWAR,AAAAAAAAWAR;AAAAAAAWAR
2,ENSG00000112658__ENST00000265354__uORF__2__ATG,NaN,NaN,NaN,NaN,AAAAAAPIPR;AAAAAPIPR;MAAAAAAPIPR,AAAAAAPIPR;AAAAAPIPR;MAAAAAAPIPR
3,ENST00000604259_1_273,FFQSFSDALIDQDPQAALEELTK,FFQSFSDALIDQDPQAALEELTK,LEELTKALEQKP,NaN,NaN,NaN
4,TCONS_00021881_241_567,NaN,NaN,NaN,NaN,SVIGNLGGGAK,SVIGNLGGGAK
...,...,...,...,...,...,...,...
906,TCONS_00012546_485_562,NaN,NaN,NaN,NaN,MYISSNGLWVR;YISSNGLWVR,MYISSNGLWVR;YISSNGLWVR
907,ENST00000578759_764_3556,AIQHWLTESAR;ALLEFAQGR;ASDPAAYVSHLPVHQDGSCNGLQH...,NaN,AIQHWLTESAR;ASDPAAYVSHLPVHQDGSCNGLQHYAALGR;CLE...,VSAQVQALQNHYR,ITYTHNGDISR;QVLEGFITR;RVLDLVLQL,NaN
908,ENSG00000162631__TCONS_00010433__ncRNA__10__ATG,NaN,NaN,NaN,NaN,RAIALLNYY,RAIALLNYY
909,ENSG00000041880__TCONS_00610801__ncRNA__3__CTG,NaN,NaN,NaN,NaN,LCFTPLVAK,LCFTPLVAK
910,ENSG00000278834__ENST00000619697__ncRNA__1__TTG,NaN,NaN,NaN,NaN,VLYEGLESK,VLYEGLESK

In [46]:
df2 = pd.read_csv("unique_peptides.csv")
df2

                                           Protein.Ids              Sequence
0      ENSG00000001167__ENST00000341376__Trunc__0__ATG         MVPGAGSVPAIQR
1      ENSG00000001167__ENST00000341376__Trunc__0__ATG          VPGAGSVPAIQR
2    ENSG00000009950_ENSG00000274080__TCONS_0076679...     GILTPELAPLGPSIQSR
3       ENSG00000019169__ENST00000327097__iORF__5__CTG               LQWSLSK
4    ENSG00000019485__TCONS_00127435__ncRNA__2__AGG...  EELDILVTEVTHHEAVLFGR
..                                                 ...                   ...
785                            TCONS_00881198_562_4443    ISSFLDQQAILFVDTADR
786                             TCONS_00893361_29_2134             LQELIPLQK
787         XLOC_005312__TCONS_00005560__ncRNA__0__AGG              MLSTHPDR
788         XLOC_005388__TCONS_00026694__ncRNA__1__CTG               LIDVLMK
789        XLOC_028088__TCONS_00224157__ncRNA__12__ATG            MILLLGTSER

[790 rows x 2 columns]

In [47]:
dfp =pd.read_parquet('20251022_Neo_TG_vanHeesch_FF.parquet', engine='fastparquet')
dfp

,Run.Index,Run,Channel,Precursor.Id,Modified.Sequence,Stripped.Sequence,Precursor.Charge,Precursor.Lib.Index,Decoy,Proteotypic,...,Translated.Q.Value,Channel.Q.Value,PG.Q.Value,PG.PEP,GG.Q.Value,Protein.Q.Value,Global.PG.Q.Value,Lib.PG.Q.Value,Best.Fr.Mz,Best.Fr.Mz.Delta
0,0.0,20230505_Felina_EwS_FF_DIA_SC_P_A089_H1_1_13264,,AAAAAAAAAAAAAAAGAGAGAK3,AAAAAAAAAAAAAAAGAGAGAK,AAAAAAAAAAAAAAAGAGAGAK,3.0,0.0,0.0,0.0,...,0.0,0.0,0.000147,0.000281,0.000167,1.0,0.000094,0.000084,640.341309,0.005005
1,1.0,20230505_Felina_EwS_FF_DIA_SC_P_A089_H1_1_13266,,AAAAAAAAAAAAAAAGAGAGAK3,AAAAAAAAAAAAAAAGAGAGAK,AAAAAAAAAAAAAAAGAGAGAK,3.0,0.0,0.0,0.0,...,0.0,0.0,0.000139,0.000275,0.000155,1.0,0.000094,0.000084,602.325623,-0.004150
2,2.0,20230508_Felina_EwS_FF_DIA_SC_P_A090_G1_1_13268,,AAAAAAAAAAAAAAAGAGAGAK3,AAAAAAAAAAAAAAAGAGAGAK,AAAAAAAAAAAAAAAGAGAGAK,3.0,0.0,0.0,0.0,...,0.0,0.0,0.000108,0.000214,0.000136,1.0,0.000094,0.000084,640.341309,0.007385
3,3.0,20230508_Felina_EwS_FF_DIA_SC_P_A092_F1_1_13270,,AAAAAAAAAAAAAAAGAGAGAK3,AAAAAAAAAAAAAAAGAGAGAK,AAAAAAAAAAAAAAAGAGAGAK,3.0,0.0,0.0,0.0,...,0.0,0.0,0.000109,0.000218,0.000124,1.0,0.000094,0.000084,640.341309,-0.002686
4,4.0,20230508_Felina_EwS_FF_DIA_SC_P_A094_E1_1_13272,,AAAAAAAAAAAAAAAGAGAGAK3,AAAAAAAAAAAAAAAGAGAGAK,AAAAAAAAAAAAAAAGAGAGAK,3.0,0.0,0.0,0.0,...,0.0,0.0,0.000110,0.000219,0.000130,1.0,0.000094,0.000084,356.192841,0.002777
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6703883,53.0,20230508_Felina_EwS_FF_DIA_SC_P_A157_D7_1_13372,,YYYWVINPADSSGITPK2,YYYWVINPADSSGITPK,YYYWVINPADSSGITPK,2.0,196569.0,0.0,0.0,...,0.0,0.0,0.000111,0.000220,0.000137,1.0,0.000094,0.000084,1086.542603,0.015747
6703884,54.0,20230508_Felina_EwS_FF_DIA_SC_P_A158_C7_1_13374,,YYYWVINPADSSGITPK2,YYYWVINPADSSGITPK,YYYWVINPADSSGITPK,2.0,196569.0,0.0,0.0,...,0.0,0.0,0.000121,0.000230,0.000138,1.0,0.000094,0.000084,972.499634,0.001953
6703885,55.0,20230508_Felina_EwS_FF_DIA_SC_P_A159_B7_1_13376,,YYYWVINPADSSGITPK2,YYYWVINPADSSGITPK,YYYWVINPADSSGITPK,2.0,196569.0,0.0,0.0,...,0.0,0.0,0.000110,0.000219,0.000139,1.0,0.000094,0.000084,972.499634,0.008179
6703886,56.0,20230508_Felina_EwS_FF_DIA_SC_P_A160_A7_1_13378,,YYYWVINPADSSGITPK2,YYYWVINPADSSGITPK,YYYWVINPADSSGITPK,2.0,196569.0,0.0,0.0,...,0.0,0.0,0.003748,0.103836,0.004223,1.0,0.000094,0.000084,1298.695068,0.020874
6703887,61.0,20230508_Felina_EwS_FF_DIA_SC_P_A169_D8_1_13388,,YYYWVINPADSSGITPK2,YYYWVINPADSSGITPK,YYYWVINPADSSGITPK,2.0,196569.0,0.0,0.0,...,0.0,0.0,0.000117,0.000233,0.000149,1.0,0.000094,0.000084,1199.626587,0.012207

In [48]:
df3 = dfp[dfp['Proteotypic'] == 1.0]
df3

,Run.Index,Run,Channel,Precursor.Id,Modified.Sequence,Stripped.Sequence,Precursor.Charge,Precursor.Lib.Index,Decoy,Proteotypic,...,Translated.Q.Value,Channel.Q.Value,PG.Q.Value,PG.PEP,GG.Q.Value,Protein.Q.Value,Global.PG.Q.Value,Lib.PG.Q.Value,Best.Fr.Mz,Best.Fr.Mz.Delta
114,4.0,20230508_Felina_EwS_FF_DIA_SC_P_A094_E1_1_13272,,AAAAAAAAAAAAAAGTR2,AAAAAAAAAAAAAAGTR,AAAAAAAAAAAAAAGTR,2.0,3.0,0.0,1.0,...,0.0,0.0,0.000110,0.000219,0.000130,0.000249,0.000094,0.000084,617.336548,0.001892
115,8.0,20230508_Felina_EwS_FF_DIA_SC_P_A103_A1_1_13280,,AAAAAAAAAAAAAAGTR2,AAAAAAAAAAAAAAGTR,AAAAAAAAAAAAAAGTR,2.0,3.0,0.0,1.0,...,0.0,0.0,0.000106,0.000212,0.000132,0.000294,0.000094,0.000084,759.410767,-0.001404
116,9.0,20230508_Felina_EwS_FF_DIA_SC_P_A104_H2_1_13282,,AAAAAAAAAAAAAAGTR2,AAAAAAAAAAAAAAGTR,AAAAAAAAAAAAAAGTR,2.0,3.0,0.0,1.0,...,0.0,0.0,0.000105,0.000209,0.000128,0.000283,0.000094,0.000084,901.484985,0.000671
117,10.0,20230508_Felina_EwS_FF_DIA_SC_P_A106_G2_1_13284,,AAAAAAAAAAAAAAGTR2,AAAAAAAAAAAAAAGTR,AAAAAAAAAAAAAAGTR,2.0,3.0,0.0,1.0,...,0.0,0.0,0.000107,0.000213,0.000123,0.000258,0.000094,0.000084,901.484985,-0.003174
118,11.0,20230508_Felina_EwS_FF_DIA_SC_P_A108_F2_1_13286,,AAAAAAAAAAAAAAGTR2,AAAAAAAAAAAAAAGTR,AAAAAAAAAAAAAAGTR,2.0,3.0,0.0,1.0,...,0.0,0.0,0.000107,0.000214,0.000138,0.000286,0.000094,0.000084,972.522095,0.002014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6703848,54.0,20230508_Felina_EwS_FF_DIA_SC_P_A158_C7_1_13374,,YYYWAVNPQDR2,YYYWAVNPQDR,YYYWAVNPQDR,2.0,196568.0,0.0,1.0,...,0.0,0.0,0.000121,0.000230,0.000138,0.000310,0.000094,0.000084,799.405701,0.003906
6703849,55.0,20230508_Felina_EwS_FF_DIA_SC_P_A159_B7_1_13376,,YYYWAVNPQDR2,YYYWAVNPQDR,YYYWAVNPQDR,2.0,196568.0,0.0,1.0,...,0.0,0.0,0.000110,0.000219,0.000139,0.000308,0.000094,0.000084,799.405701,0.000366
6703850,58.0,20230508_Felina_EwS_FF_DIA_SC_P_A165_G8_1_13382,,YYYWAVNPQDR2,YYYWAVNPQDR,YYYWAVNPQDR,2.0,196568.0,0.0,1.0,...,0.0,0.0,0.000147,0.000285,0.000161,0.000339,0.000094,0.000084,629.300171,0.004639
6703851,60.0,20230508_Felina_EwS_FF_DIA_SC_P_A168_E8_1_13386,,YYYWAVNPQDR2,YYYWAVNPQDR,YYYWAVNPQDR,2.0,196568.0,0.0,1.0,...,0.0,0.0,0.000144,0.000280,0.000160,0.000333,0.000094,0.000084,1148.548340,0.010498
6703852,61.0,20230508_Felina_EwS_FF_DIA_SC_P_A169_D8_1_13388,,YYYWAVNPQDR2,YYYWAVNPQDR,YYYWAVNPQDR,2.0,196568.0,0.0,1.0,...,0.0,0.0,0.000117,0.000233,0.000149,0.000307,0.000094,0.000084,799.405701,0.003845

In [49]:
dff = df3[['Protein.Group', 'Stripped.Sequence']]
dff = dff.groupby(['Protein.Group'])['Stripped.Sequence'].apply(';'.join)
dff

Protein.Group
A0A075B6H9                     FSGSSSGAER;FSGSSSGAER;FSGSSSGAER;FSGSSSGAER;FS...
A0A075B6I0                     FSGSILGNK;FSGSILGNK;FSGSILGNK;FSGSILGNK;FSGSIL...
A0A075B6I1                     FSGSSSGADR;FSGSSSGADR;FSGSSSGADR;FSGSSSGADR;FS...
A0A075B6I4                     NNNRPSGISER;NNNRPSGISER;NNNRPSGISER;NNNRPSGISE...
A0A075B6I6                                             PSGVPDQFSGSK;PSGVPDQFSGSK
                                                     ...
rev_sp|Q9Y4K1|CRBG1_HUMAN                                            EPLKPSAVVDK
rev_sp|Q9Y5Y9|SCNAA_HUMAN                                          LSDLEGSEGLVNK
rev_sp|Q9Y663|HS3SA_HUMAN      LGLFDQVR;LGLFDQVR;LGLFDQVR;LGLFDQVR;LGLFDQVR;L...
rev_sp|Q9Y6A2-3|CP46A_HUMAN    AELIEVLQEAKENFTE;AELIEVLQEAKENFTE;AELIEVLQEAKE...
rev_sp|Q9Y6L6|SO1B1_HUMAN      AIGVTNLK;AIGVTNLK;AIGVTNLK;AIGVTNLK;AIGVTNLK;A...
Name: Stripped.Sequence, Length: 8474, dtype: str

In [50]:

d3 = pd.DataFrame({'protein':dff.index, '3_peptides_proteotypic':dff.values})
d3['protein'] = d3['protein'].apply(lambda x: x.split(';'))
d3 = d3.explode('protein')
d3

,protein,3_peptides_proteotypic
0,A0A075B6H9,FSGSSSGAER;FSGSSSGAER;FSGSSSGAER;FSGSSSGAER;FS...
1,A0A075B6I0,FSGSILGNK;FSGSILGNK;FSGSILGNK;FSGSILGNK;FSGSIL...
2,A0A075B6I1,FSGSSSGADR;FSGSSSGADR;FSGSSSGADR;FSGSSSGADR;FS...
3,A0A075B6I4,NNNRPSGISER;NNNRPSGISER;NNNRPSGISER;NNNRPSGISE...
4,A0A075B6I6,PSGVPDQFSGSK;PSGVPDQFSGSK
...,...,...
8469,rev_sp|Q9Y4K1|CRBG1_HUMAN,EPLKPSAVVDK
8470,rev_sp|Q9Y5Y9|SCNAA_HUMAN,LSDLEGSEGLVNK
8471,rev_sp|Q9Y663|HS3SA_HUMAN,LGLFDQVR;LGLFDQVR;LGLFDQVR;LGLFDQVR;LGLFDQVR;L...
8472,rev_sp|Q9Y6A2-3|CP46A_HUMAN,AELIEVLQEAKENFTE;AELIEVLQEAKENFTE;AELIEVLQEAKE...
8473,rev_sp|Q9Y6L6|SO1B1_HUMAN,AIGVTNLK;AIGVTNLK;AIGVTNLK;AIGVTNLK;AIGVTNLK;A...

In [51]:
d3['protein'] = d3['protein'].str.replace('_NEOTRANSCRIPT', '', regex=False)

In [52]:
merge = df.merge(d3, how='left', on='protein')
merge

,protein,1_peptides,1_peptides_no_match_sp,2_peptides,2_peptides_no_match_sp,4_peptides,4_peptides_no_match_sp,3_peptides_proteotypic
0,ENST00000291041_23_121,NaN,NaN,NaN,NaN,AAAAAAAAIAR,AAAAAAAAIAR,NaN
1,ENST00000303204_18_68,NaN,NaN,NaN,NaN,AAAAAAAAWAR;AAAAAAAWAR,AAAAAAAAWAR;AAAAAAAWAR,NaN
2,ENSG00000112658__ENST00000265354__uORF__2__ATG,NaN,NaN,NaN,NaN,AAAAAAPIPR;AAAAAPIPR;MAAAAAAPIPR,AAAAAAPIPR;AAAAAPIPR;MAAAAAAPIPR,NaN
3,ENST00000604259_1_273,FFQSFSDALIDQDPQAALEELTK,FFQSFSDALIDQDPQAALEELTK,LEELTKALEQKP,NaN,NaN,NaN,NaN
4,TCONS_00021881_241_567,NaN,NaN,NaN,NaN,SVIGNLGGGAK,SVIGNLGGGAK,NaN
...,...,...,...,...,...,...,...,...
906,TCONS_00012546_485_562,NaN,NaN,NaN,NaN,MYISSNGLWVR;YISSNGLWVR,MYISSNGLWVR;YISSNGLWVR,NaN
907,ENST00000578759_764_3556,AIQHWLTESAR;ALLEFAQGR;ASDPAAYVSHLPVHQDGSCNGLQH...,NaN,AIQHWLTESAR;ASDPAAYVSHLPVHQDGSCNGLQHYAALGR;CLE...,VSAQVQALQNHYR,ITYTHNGDISR;QVLEGFITR;RVLDLVLQL,NaN,NaN
908,ENSG00000162631__TCONS_00010433__ncRNA__10__ATG,NaN,NaN,NaN,NaN,RAIALLNYY,RAIALLNYY,NaN
909,ENSG00000041880__TCONS_00610801__ncRNA__3__CTG,NaN,NaN,NaN,NaN,LCFTPLVAK,LCFTPLVAK,NaN
910,ENSG00000278834__ENST00000619697__ncRNA__1__TTG,NaN,NaN,NaN,NaN,VLYEGLESK,VLYEGLESK,NaN

In [53]:
df3 = dfp[dfp['Proteotypic'] == 0.0]
df3

,Run.Index,Run,Channel,Precursor.Id,Modified.Sequence,Stripped.Sequence,Precursor.Charge,Precursor.Lib.Index,Decoy,Proteotypic,...,Translated.Q.Value,Channel.Q.Value,PG.Q.Value,PG.PEP,GG.Q.Value,Protein.Q.Value,Global.PG.Q.Value,Lib.PG.Q.Value,Best.Fr.Mz,Best.Fr.Mz.Delta
0,0.0,20230505_Felina_EwS_FF_DIA_SC_P_A089_H1_1_13264,,AAAAAAAAAAAAAAAGAGAGAK3,AAAAAAAAAAAAAAAGAGAGAK,AAAAAAAAAAAAAAAGAGAGAK,3.0,0.0,0.0,0.0,...,0.0,0.0,0.000147,0.000281,0.000167,1.0,0.000094,0.000084,640.341309,0.005005
1,1.0,20230505_Felina_EwS_FF_DIA_SC_P_A089_H1_1_13266,,AAAAAAAAAAAAAAAGAGAGAK3,AAAAAAAAAAAAAAAGAGAGAK,AAAAAAAAAAAAAAAGAGAGAK,3.0,0.0,0.0,0.0,...,0.0,0.0,0.000139,0.000275,0.000155,1.0,0.000094,0.000084,602.325623,-0.004150
2,2.0,20230508_Felina_EwS_FF_DIA_SC_P_A090_G1_1_13268,,AAAAAAAAAAAAAAAGAGAGAK3,AAAAAAAAAAAAAAAGAGAGAK,AAAAAAAAAAAAAAAGAGAGAK,3.0,0.0,0.0,0.0,...,0.0,0.0,0.000108,0.000214,0.000136,1.0,0.000094,0.000084,640.341309,0.007385
3,3.0,20230508_Felina_EwS_FF_DIA_SC_P_A092_F1_1_13270,,AAAAAAAAAAAAAAAGAGAGAK3,AAAAAAAAAAAAAAAGAGAGAK,AAAAAAAAAAAAAAAGAGAGAK,3.0,0.0,0.0,0.0,...,0.0,0.0,0.000109,0.000218,0.000124,1.0,0.000094,0.000084,640.341309,-0.002686
4,4.0,20230508_Felina_EwS_FF_DIA_SC_P_A094_E1_1_13272,,AAAAAAAAAAAAAAAGAGAGAK3,AAAAAAAAAAAAAAAGAGAGAK,AAAAAAAAAAAAAAAGAGAGAK,3.0,0.0,0.0,0.0,...,0.0,0.0,0.000110,0.000219,0.000130,1.0,0.000094,0.000084,356.192841,0.002777
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6703883,53.0,20230508_Felina_EwS_FF_DIA_SC_P_A157_D7_1_13372,,YYYWVINPADSSGITPK2,YYYWVINPADSSGITPK,YYYWVINPADSSGITPK,2.0,196569.0,0.0,0.0,...,0.0,0.0,0.000111,0.000220,0.000137,1.0,0.000094,0.000084,1086.542603,0.015747
6703884,54.0,20230508_Felina_EwS_FF_DIA_SC_P_A158_C7_1_13374,,YYYWVINPADSSGITPK2,YYYWVINPADSSGITPK,YYYWVINPADSSGITPK,2.0,196569.0,0.0,0.0,...,0.0,0.0,0.000121,0.000230,0.000138,1.0,0.000094,0.000084,972.499634,0.001953
6703885,55.0,20230508_Felina_EwS_FF_DIA_SC_P_A159_B7_1_13376,,YYYWVINPADSSGITPK2,YYYWVINPADSSGITPK,YYYWVINPADSSGITPK,2.0,196569.0,0.0,0.0,...,0.0,0.0,0.000110,0.000219,0.000139,1.0,0.000094,0.000084,972.499634,0.008179
6703886,56.0,20230508_Felina_EwS_FF_DIA_SC_P_A160_A7_1_13378,,YYYWVINPADSSGITPK2,YYYWVINPADSSGITPK,YYYWVINPADSSGITPK,2.0,196569.0,0.0,0.0,...,0.0,0.0,0.003748,0.103836,0.004223,1.0,0.000094,0.000084,1298.695068,0.020874
6703887,61.0,20230508_Felina_EwS_FF_DIA_SC_P_A169_D8_1_13388,,YYYWVINPADSSGITPK2,YYYWVINPADSSGITPK,YYYWVINPADSSGITPK,2.0,196569.0,0.0,0.0,...,0.0,0.0,0.000117,0.000233,0.000149,1.0,0.000094,0.000084,1199.626587,0.012207

In [54]:
dff = df3[['Protein.Group', 'Stripped.Sequence']]
dff = dff.groupby(['Protein.Group'])['Stripped.Sequence'].apply(';'.join)
dff

Protein.Group
A0A024RBG1;Q9NZJ9-2                                                                                              LLGIFEQNQDR;LLGIFEQNQDR;LLGIFEQNQDR;LLGIFEQNQD...
A0A075B6H7                                                                                                       LLIYGASTR;LLIYGASTR;LLIYGASTR;LLIYGASTR;LLIYGA...
A0A075B6I6                                                                                                       LLIYGNSNR;LLIYGNSNR;LLIYGNSNR;LLIYGNSNR;LLIYGN...
A0A075B6I9                                                                                                       FSGSLLGGK;FSGSLLGGK;FSGSLLGGK;FSGSLLGGK;FSGSLL...
A0A075B6J9                                                                                                       LMIYEVSNR;LMIYEVSNR;LMIYEVSNR;LMIYEVSNR;LMIYEV...
                                                                                                                                       ...
rev_sp|Q9Y5E9|PCDBE_HUMAN                                                                                        RLDLAGR;RLDLAGR;RLDLAGR;RLDLAGR;RLDLAGR;RLDLAG...
rev_sp|Q9Y5H7-3|PCDA5_HUMAN                                                                                      LLFSVQTQK;LLFSVQTQK;LLFSVQTQK;LLFSVQTQK;LLFSVQ...
rev_sp|Q9Y5W7-2|SNX14_HUMAN;rev_sp|Q9Y5W7-3|SNX14_HUMAN;rev_sp|Q9Y5W7-4|SNX14_HUMAN;rev_sp|Q9Y5W7|SNX14_HUMAN    FLLDQQER;FLLDQQER;FLLDQQER;FLLDQQER;FLLDQQER;F...
rev_sp|Q9Y6R4|M3K4_HUMAN                                                                                         PLVSDGGSPSPR;PLVSDGGSPSPR;PLVSDGGSPSPR;PLVSDGG...
rev_sp|Q9Y6X9|MORC2_HUMAN;rev_sp|Q9Y6X9-2|MORC2_HUMAN                                                            IKETLQK;IKETLQK;IKETLQK;IKETLQK;IKETLQK;IKETLQ...
Name: Stripped.Sequence, Length: 10623, dtype: str

In [55]:

d3 = pd.DataFrame({'protein':dff.index, '3_peptides_not_proteotypic':dff.values})
d3['protein'] = d3['protein'].apply(lambda x: x.split(';'))
d3 = d3.explode('protein')
d3['protein'] = d3['protein'].str.replace('_NEOTRANSCRIPT', '', regex=False)
d3

,protein,3_peptides_not_proteotypic
0,A0A024RBG1,LLGIFEQNQDR;LLGIFEQNQDR;LLGIFEQNQDR;LLGIFEQNQD...
0,Q9NZJ9-2,LLGIFEQNQDR;LLGIFEQNQDR;LLGIFEQNQDR;LLGIFEQNQD...
1,A0A075B6H7,LLIYGASTR;LLIYGASTR;LLIYGASTR;LLIYGASTR;LLIYGA...
2,A0A075B6I6,LLIYGNSNR;LLIYGNSNR;LLIYGNSNR;LLIYGNSNR;LLIYGN...
3,A0A075B6I9,FSGSLLGGK;FSGSLLGGK;FSGSLLGGK;FSGSLLGGK;FSGSLL...
...,...,...
10620,rev_sp|Q9Y5W7-4|SNX14_HUMAN,FLLDQQER;FLLDQQER;FLLDQQER;FLLDQQER;FLLDQQER;F...
10620,rev_sp|Q9Y5W7|SNX14_HUMAN,FLLDQQER;FLLDQQER;FLLDQQER;FLLDQQER;FLLDQQER;F...
10621,rev_sp|Q9Y6R4|M3K4_HUMAN,PLVSDGGSPSPR;PLVSDGGSPSPR;PLVSDGGSPSPR;PLVSDGG...
10622,rev_sp|Q9Y6X9|MORC2_HUMAN,IKETLQK;IKETLQK;IKETLQK;IKETLQK;IKETLQK;IKETLQ...
10622,rev_sp|Q9Y6X9-2|MORC2_HUMAN,IKETLQK;IKETLQK;IKETLQK;IKETLQK;IKETLQK;IKETLQ...

In [56]:
merge = merge.merge(d3, how='left', on='protein')
merge

,protein,1_peptides,1_peptides_no_match_sp,2_peptides,2_peptides_no_match_sp,4_peptides,4_peptides_no_match_sp,3_peptides_proteotypic,3_peptides_not_proteotypic
0,ENST00000291041_23_121,NaN,NaN,NaN,NaN,AAAAAAAAIAR,AAAAAAAAIAR,NaN,NaN
1,ENST00000303204_18_68,NaN,NaN,NaN,NaN,AAAAAAAAWAR;AAAAAAAWAR,AAAAAAAAWAR;AAAAAAAWAR,NaN,NaN
2,ENSG00000112658__ENST00000265354__uORF__2__ATG,NaN,NaN,NaN,NaN,AAAAAAPIPR;AAAAAPIPR;MAAAAAAPIPR,AAAAAAPIPR;AAAAAPIPR;MAAAAAAPIPR,NaN,NaN
3,ENST00000604259_1_273,FFQSFSDALIDQDPQAALEELTK,FFQSFSDALIDQDPQAALEELTK,LEELTKALEQKP,NaN,NaN,NaN,NaN,NaN
4,TCONS_00021881_241_567,NaN,NaN,NaN,NaN,SVIGNLGGGAK,SVIGNLGGGAK,NaN,NaN
...,...,...,...,...,...,...,...,...,...
906,TCONS_00012546_485_562,NaN,NaN,NaN,NaN,MYISSNGLWVR;YISSNGLWVR,MYISSNGLWVR;YISSNGLWVR,NaN,NaN
907,ENST00000578759_764_3556,AIQHWLTESAR;ALLEFAQGR;ASDPAAYVSHLPVHQDGSCNGLQH...,NaN,AIQHWLTESAR;ASDPAAYVSHLPVHQDGSCNGLQHYAALGR;CLE...,VSAQVQALQNHYR,ITYTHNGDISR;QVLEGFITR;RVLDLVLQL,NaN,NaN,NaN
908,ENSG00000162631__TCONS_00010433__ncRNA__10__ATG,NaN,NaN,NaN,NaN,RAIALLNYY,RAIALLNYY,NaN,NaN
909,ENSG00000041880__TCONS_00610801__ncRNA__3__CTG,NaN,NaN,NaN,NaN,LCFTPLVAK,LCFTPLVAK,NaN,NaN
910,ENSG00000278834__ENST00000619697__ncRNA__1__TTG,NaN,NaN,NaN,NaN,VLYEGLESK,VLYEGLESK,NaN,NaN

In [57]:
merge[['protein', '1_peptides', '1_peptides_no_match_sp', '2_peptides', '2_peptides_no_match_sp', '3_peptides_proteotypic', '3_peptides_not_proteotypic', '4_peptides', '4_peptides_no_match_sp']].to_csv('peptides_by_protein_merged.csv', index=False)