In [17]:
import pandas as pd
from Bio import SeqIO
import re

In [18]:

def safe_id(prot_id: str) -> str:
    return re.sub(r"[|/\\:*?\"<> ]", "_", prot_id)

In [6]:
def fasta_to_df(path: str, n: int = None) -> pd.DataFrame:
    records = []
    for record in SeqIO.parse(path, "fasta"):
        records.append({
            "id":          record.id,
            "description": record.description,
            "sequence":    str(record.seq),
            "length":      len(record.seq),
        })
        if n and len(records) >= n:
            break
    return pd.DataFrame(records)

In [3]:
meta = pd.read_csv('../data/meta/20260219_EwS_ncORF_metadata_summary.tsv', sep='\t')
meta

,orf_id,ORF_ranges,Protein,gene_id,gene_biotype,gene_name,transcript_id,uniprot_gn_ids,cl_mean,ps_mean,...,Number_SB,Peptides_WB,Number_WB,class,any_peptide_found_in_IP,result_A673,result_SKNMC,result_MHHES,result_TC106,result_RDES
0,ENSG00000159167__ENST00000290271__uORF__2__GTG,8:23854633-23854746,MAAAAAAAAAAAAAEAPVAAAASPATTTKKNPHQILT,ENSG00000159167,protein_coding,STC1,ENST00000290271,A0A0H3W641;P52823,1.187192,2.508946,...,NaN,NaN,NaN,0.0,False,not expressed,not expressed,upregulated,ns,ns
1,ENST00000291041_23_121,16:67893276-67908682,MAAAAAAAAAAAIARRWPAEPPRRRRARRPREV,ENSG00000159792,protein_coding,PSKH1,ENST00000291041,P11801;A0A087WZT9,23.079040,17.597305,...,NaN,NaN,NaN,1.0,True,ns,ns,ns,ns,ns
2,ENST00000216727_182_1099,14:23321470-23325283,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...,ENSG00000100836,protein_coding,PABPN1,ENST00000216727,B4DEH8;Q86U42;G3V4T2,72.570950,51.634440,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ENST00000397276_14_901,14:23321470-23324296,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...,ENSG00000100836,protein_coding,PABPN1,ENST00000397276,B4DEH8;Q86U42;G3V4T2,71.136807,50.211111,...,NaN,NaN,NaN,NaN,NaN,ns,ns,ns,ns,ns
4,ENST00000354300_17_85,12:110583234-110583302,MAAAAAAAAAGTSVGLRRRSRRF,ENSG00000196850,protein_coding,PPTC7,ENST00000354300,Q8NI37,14.741234,14.913901,...,NaN,NaN,NaN,0.0,False,not expressed,ns,upregulated,ns,ns
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62178,ENSG00000116604__TCONS_00065632__ncRNA__9__ATT,1:156483398-156500599,MYYSPRPELRLPGVEDPPDQGRGLPALCRDNTVPPAGLEAVQKVSCRP,ENSG00000116604,protein_coding,MEF2D,TCONS_00065632,Q14814;Q05BX2,12.438524,33.178861,...,NaN,NaN,NaN,0.0,False,ns,ns,ns,ns,ns
62179,ENST00000552151_8_454,12:70310970-70330470,MYYSQSSMFPHRSEKDMLASPSTSGQLSQFGASLYGQQSALGLPMR...,ENSG00000111596,protein_coding,CNOT2,ENST00000552151,F8VSK9;Q9NZN8;F8VUB4;F8W145;F8VPX5;F8VVY1;F8VV...,12.182117,23.360930,...,NaN,NaN,NaN,NaN,NaN,ns,ns,ns,ns,ns
62180,ENST00000495930_268_459,13:112875798-112875989,MYYVFIQMLSSGPAWLAIVLLVTISLLPDVLKKVLCRQLWPTATER...,ENSG00000068650,protein_coding,ATP11A,ENST00000495930,P98196;E9PEJ6;A2A3G9;A0A087WVE8,6.739418,19.103163,...,NaN,NaN,NaN,NaN,NaN,not expressed,ns,ns,ns,ns
62181,ENSG00000181392_ENSG00000239382__ENST000004904...,19:36010923-36013077,MYYVPDFISKEEEEYLLRQVFNAPKPKWTQLSGRKLQNWGPHCLPQ...,ENSG00000239382,protein_coding,ALKBH6,ENST00000490483,Q3KRA9;E9PI76;S4R3C7;H0YD83,10.796175,7.697037,...,NaN,NaN,NaN,NaN,NaN,ns,ns,ns,ns,ns
62182,ENST00000507377_491_1471,4:128091430-128122230,MYYYDDGTGVQVYPVEEALLKEYIKRQIEYYFSVENLERDFFLRGK...,ENSG00000138709,protein_coding,LARP1B,ENST00000507377,Q659C4;G3V0E9;A0A994J4X5;D6RJB0;A0A994J4H9;D6R...,2.507563,3.846579,...,NaN,NaN,NaN,NaN,NaN,ns,ns,ns,ns,ns

In [8]:
up = fasta_to_df('../data/uniprot/uniprotkb_with_isoforms_reviewed_true_AND_model_organ_2024_10_29.fasta')

In [9]:
up

,id,description,sequence,length
0,sp|A0A087X1C5|CP2D7_HUMAN,sp|A0A087X1C5|CP2D7_HUMAN Putative cytochrome ...,MGLEALVPLAMIVAIFLLLVDLMHRHQRWAARYPPGPLPLPGLGNL...,515
1,sp|A0A0B4J2F0|PIOS1_HUMAN,sp|A0A0B4J2F0|PIOS1_HUMAN Protein PIGBOS1 OS=H...,MFRRLTFAQLLFATVLGIAGGVYIFQPVFEQYAKDQKELKEKMQLV...,54
2,sp|A0A0B4J2F2|SIK1B_HUMAN,sp|A0A0B4J2F2|SIK1B_HUMAN Putative serine/thre...,MVIMSEFSADPAGQGQGQQKPLRVGFYDIERTLGKGNFAVVKLARH...,783
3,sp|A0A0C5B5G6|MOTSC_HUMAN,sp|A0A0C5B5G6|MOTSC_HUMAN Mitochondrial-derive...,MRWQEMGYIFYPRKLR,16
4,sp|A0A0K2S4Q6|CD3CH_HUMAN,sp|A0A0K2S4Q6|CD3CH_HUMAN Protein CD300H OS=Ho...,MTQRAGAAMLPSALLLLCVPGCLTVSGPSTVMGAVGESLSVQCRYE...,201
...,...,...,...,...
42515,sp|Q9Y6S9-4|RPKL1_HUMAN,sp|Q9Y6S9-4|RPKL1_HUMAN Isoform 4 of Ribosomal...,MSLVACECLPSPGLEPEPCSRARSQAHVYLEQIRNRVALGVPDMTK...,255
42516,sp|Q9Y6V7-2|DDX49_HUMAN,sp|Q9Y6V7-2|DDX49_HUMAN Isoform 2 of Probable ...,MDMVAQALELSRKPHVVIATPGRLADHLRSSNTFSIKKIRFLVMDE...,254
42517,sp|Q9Y6X4-2|F169A_HUMAN,sp|Q9Y6X4-2|F169A_HUMAN Isoform 2 of Soluble l...,MAFPVDMLENCSHEELENSAEDYMSDLRCGDPENPECFSLLNITIP...,127
42518,sp|Q9Y6Y8-2|S23IP_HUMAN,sp|Q9Y6Y8-2|S23IP_HUMAN Isoform 2 of SEC23-int...,MAERKPNGGSGGASTSSSGTNLLFSSSATEFSFNVPFIPVTQASAS...,924
42519,sp|Q9Y6Z2|CF123_HUMAN,sp|Q9Y6Z2|CF123_HUMAN Uncharacterized protein ...,MGTAVGPHHSPAPHDSALPARLLTSDFPYGRSCQIEQVKYSVPDTG...,57

In [10]:
ng = meta[meta['orf_category_new'] == 'neogene ORF']
ng

,orf_id,ORF_ranges,Protein,gene_id,gene_biotype,gene_name,transcript_id,uniprot_gn_ids,cl_mean,ps_mean,...,Number_SB,Peptides_WB,Number_WB,class,any_peptide_found_in_IP,result_A673,result_SKNMC,result_MHHES,result_TC106,result_RDES
430,ENSG00000264589__TCONS_00371165__ncRNA__10__ATG,17:45827087-45827659,MAAALGDCSSHPSSFRRRD,ENSG00000264589,lncRNA,MAPT-AS1,TCONS_00371165,NaN,0.624697,4.249496,...,NaN,"DCSSHPSSF,CSSHPSSFR,SSHPSSFRR",3.0,0.0,False,not expressed,not expressed,ns,not expressed,not expressed
444,Ew_NG49.1_739_987,20:4248311-4248559,MAAALRSVMMAGYLSEWRTPTYRSTEMVQRLRMEAVQHSTSTAAHT...,Ew_NG49,unannotated gene,Ew_NG49,Ew_NG49.1,NaN,6.045038,5.750445,...,25.0,"SVMMAGYLSEW,GYLSEWRTPTY,WRTPTYRSTEM,TYRSTEMVQR...",67.0,0.0,False,ns,not expressed,ns,ns,ns
763,Ew_NG11.5_130_312,10:26640299-26668431,MAADLQYQEGSGCNKPESCVWGRREHKWIHPPSTTAQQLKTTNCGP...,ENSG00000227932,pseudogene,SELENOOLP,Ew_NG11.5,NaN,32.313113,26.088388,...,3.0,"LQYQEGSGCNK,SGCNKPESCVW,SCVWGRREHKW,IHPPSTTAQQ...",17.0,0.0,False,ns,ns,downregulated,ns,downregulated
764,TCONS_00093252_307_423,10:26664301-26668431,MAADLQYQGASSPASSSASFPEAFGSRESRLHLTYSFLG,ENSG00000227932,pseudogene,SELENOOLP,TCONS_00093252,NaN,78.485846,58.888714,...,8.0,"ASSPASSSASF,SSPASSSASFP,ASSSASFPEAF,GSRESRLHLT...",23.0,0.0,False,ns,ns,downregulated,ns,downregulated
765,Ew_NG11.9_229_285,10:26647691-26668431,MAADLQYQVYFRKAWMQQA,ENSG00000227932,pseudogene,SELENOOLP,Ew_NG11.9,NaN,79.226556,50.831669,...,5.0,"MAADLQYQVY,AADLQYQVYF,QYQVYFRKAW,MAADLQYQV,AAD...",10.0,0.0,False,ns,ns,downregulated,ns,downregulated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61039,TCONS_00113424_61_651,10:114100818-114101515,MWPHGFLAGSWALSLSGFLERVIGNGAVRESKDAERGGNRACHGQG...,XLOC_014666,unannotated gene,XLOC_014666,TCONS_00113424,NaN,0.096277,1.157796,...,33.0,"MWPHGFLAGSW,ALSLSGFLERV,VIGNGAVRESK,KAGRGGASPS...",105.0,0.0,False,not expressed,not expressed,ns,not expressed,not expressed
61441,XLOC_101091__TCONS_00808337__ncRNA__76__ATG,8:27150719-27150787,MWYLGFLFLHKFAKSNGLQLHP,XLOC_101091,unannotated gene,XLOC_101091,TCONS_00808337,NaN,0.085164,2.159126,...,4.0,"WYLGFLFLHKF,FLHKFAKSNGL,HKFAKSNGLQL,GFLFLHKFAK...",12.0,0.0,False,not expressed,not expressed,not expressed,not expressed,not expressed
61564,TCONS_00808337_15151_15279,8:27151313-27151441,MYEDSSFSTFLPTFVTVCLVNDSYYSVYVVVSHCGFYLYFPDD,XLOC_101091,unannotated gene,XLOC_101091,TCONS_00808337,NaN,7.492293,39.086036,...,15.0,"MYEDSSFSTFL,YEDSSFSTFLP,TFLPTFVTVCL,FLPTFVTVCL...",32.0,0.0,False,not expressed,ns,ns,ns,not expressed
61861,XLOC_005528__TCONS_00014527__ncRNA__1__ATG,1:18607584-18607766,MYNPRPAELSEAIMLSVTRGALESGRTPGTNCHYLPNDKADSASSE...,XLOC_005528,unannotated gene,XLOC_005528,TCONS_00014527,NaN,0.260422,1.479892,...,12.0,"AELSEAIMLSV,SGRTPGTNCHY,NPRPAELSEA,PAELSEAIML,...",30.0,0.0,False,not expressed,not expressed,ns,not expressed,ns
61931,ENSG00000238185_XLOC_028203__Ew_NG12.1__ncRNA_...,13:30998806-31001434,MYPTPDNMLAAETVKTKPRTERRANNFIPQSFTHLPLHLQPAETQT...,XLOC_028203,unannotated gene,XLOC_028203,Ew_NG12.1,NaN,62.428700,30.697065,...,8.0,"YPTPDNMLAA,MLAAETVKTK,RRANNFIPQS,RANNFIPQSF,NF...",25.0,0.0,False,downregulated,downregulated,ns,downregulated,downregulated

In [13]:
with open('neogenes.fasta', 'w') as f:
    for _, row in ng.iterrows():
        f.write(f">{row['orf_id']}\n")
        f.write(f"{row['Protein']}\n")

In [14]:
up_364 = up.sample(n=364, random_state=42)
up_364

,id,description,sequence,length
25885,sp|P22105-2|TENX_HUMAN,sp|P22105-2|TENX_HUMAN Isoform XB-short of Ten...,MRLSWSVAQGPFDSFVVQYEDTNGQPQALLVDGDQSKILISGLEPS...,673
13377,sp|Q9NVH0|EXD2_HUMAN,sp|Q9NVH0|EXD2_HUMAN Exonuclease 3'-5' domain-...,MSRQNLVALTVTTLLGVAVGGFVLWKGIQRRRRSKTSPVTQQPQQK...,621
7656,sp|Q5TBB1|RNH2B_HUMAN,sp|Q5TBB1|RNH2B_HUMAN Ribonuclease H2 subunit ...,MAAGVDCGDGVGARQHVFLVSEYLKDASKKMKNGLMFVKLVNPCSG...,312
30902,sp|Q70HW3-3|SAMC_HUMAN,sp|Q70HW3-3|SAMC_HUMAN Isoform 3 of Mitochondr...,MKHMLAASAGEVVACLIRVPSEVVKQRAQVSASTRTFQIFSNILYE...,66
11594,sp|Q99720|SGMR1_HUMAN,sp|Q99720|SGMR1_HUMAN Sigma non-opioid intrace...,MQWAVGRRWAWAALLLAVAAVLTQVVWLWLGTQSFVFQREEIAQLA...,223
...,...,...,...,...
16178,sp|Q5VTE0|EF1A3_HUMAN,sp|Q5VTE0|EF1A3_HUMAN Putative elongation fact...,MGKEKTHINIVVIGHVDSGKSTTTGHLIYKCGGIDKRTIEKFEKEA...,462
24593,sp|O94864-2|ST65G_HUMAN,sp|O94864-2|ST65G_HUMAN Isoform 2 of STAGA com...,MLRYWGEIPISSSQTNRSSFDLLPREFRLVEVHDPPLHQPSANKPK...,412
16542,sp|Q8IUZ0|LRC49_HUMAN,sp|Q8IUZ0|LRC49_HUMAN Leucine-rich repeat-cont...,MIPGKYRSVSGRAANNVNCGLHLVIQTSSLPEKNKVEFKLNKDTSS...,686
31562,sp|Q86X10-3|RLGPB_HUMAN,sp|Q86X10-3|RLGPB_HUMAN Isoform 3 of Ral GTPas...,MYSEWRSLHLVIQNDQGHTSVLHSYPESVGREVANAVVRPLGQVLG...,1491
26982,sp|P54278-3|PMS2_HUMAN,sp|P54278-3|PMS2_HUMAN Isoform 3 of Mismatch r...,MERAESSSTEPAKAIKPIDRKSVHQICSGQVVLSLSTAVKELVENS...,572

In [19]:
with open('canonical.fasta', 'w') as f:
    for _, row in up_364.iterrows():
        f.write(f">{safe_id(row['id'])}\n")
        f.write(f"{row['sequence']}\n")

In [20]:
m = pd.read_csv('metadata.csv')
m

,sample,search_engine,fdr,path,DB,hla_alleles
0,A673,Fragpipe,0.01,/mnt/raid0/ewing_sarcoma/output/Immumopeptidom...,uniprot_NT,HLA-A01:01|HLA-A02:01|HLA-B07:02|HLA-C07:02
1,EW16,Fragpipe,0.01,/mnt/raid0/ewing_sarcoma/output/Immumopeptidom...,uniprot_NT,HLA-A02:01|HLA-B44:03|HLA-B51:01|HLA-C16:01|HL...
2,EW7,Fragpipe,0.01,/mnt/raid0/ewing_sarcoma/output/Immumopeptidom...,uniprot_NT,HLA-A02:01|HLA-A03:01|HLA-B35:01|HLA-B51:01|HL...
3,STA-ET-1,Fragpipe,0.01,/mnt/raid0/ewing_sarcoma/output/Immumopeptidom...,uniprot_NT,HLA-A02:01|HLA-A30:04|HLA-B51:08|HLA-B44:02|HL...
4,TC71,Fragpipe,0.01,/mnt/raid0/ewing_sarcoma/output/Immumopeptidom...,uniprot_NT,HLA-A68:01|HLA-A02:01|HLA-B44:02|HLA-B15:01|HL...
5,IC-pPDX-8,Fragpipe,0.01,/mnt/raid0/ewing_sarcoma/output/Immumopeptidom...,uniprot_NT,HLA-A02:01|HLA-A33:03|HLA-B15:03|HLA-B51:08|HL...
6,IC-pPDX-5,Fragpipe,0.01,/mnt/raid0/ewing_sarcoma/output/Immumopeptidom...,uniprot_NT,HLA-A03:01|HLA-A02:01|HLA-B50:01|HLA-B52:01|HL...
7,IC-pPDX-164,Fragpipe,0.01,/mnt/raid0/ewing_sarcoma/output/Immumopeptidom...,uniprot_NT,HLA-A01:01|HLA-B57:01|HLA-C03:04|HLA-C07:02
8,IC-pPDX-179,Fragpipe,0.01,/mnt/raid0/ewing_sarcoma/output/Immumopeptidom...,uniprot_NT,HLA-A30:01|HLA-A32:01|HLA-B40:02|HLA-B51:01|HL...
9,IC-pPDX-141,Fragpipe,0.01,/mnt/raid0/ewing_sarcoma/output/Immumopeptidom...,uniprot_NT,HLA-A30:01|HLA-A02:01|HLA-B35:03|HLA-B44:03|HL...

In [22]:
all = []
for _, row in m.iterrows():
    a = row['hla_alleles'].split('|')
    all.extend(a)
all

['HLA-A01:01',
 'HLA-A02:01',
 'HLA-B07:02',
 'HLA-C07:02',
 'HLA-A02:01',
 'HLA-B44:03',
 'HLA-B51:01',
 'HLA-C16:01',
 'HLA-C05:01',
 'HLA-A02:01',
 'HLA-A03:01',
 'HLA-B35:01',
 'HLA-B51:01',
 'HLA-C04:01',
 'HLA-C15:02',
 'HLA-A02:01',
 'HLA-A30:04',
 'HLA-B51:08',
 'HLA-B44:02',
 'HLA-C05:01',
 'HLA-C16:02',
 'HLA-A68:01',
 'HLA-A02:01',
 'HLA-B44:02',
 'HLA-B15:01',
 'HLA-C03:03',
 'HLA-C05:01',
 'HLA-A02:01',
 'HLA-A33:03',
 'HLA-B15:03',
 'HLA-B51:08',
 'HLA-C16:02',
 'HLA-C02:10',
 'HLA-A03:01',
 'HLA-A02:01',
 'HLA-B50:01',
 'HLA-B52:01',
 'HLA-C06:02',
 'HLA-C12:02',
 'HLA-A01:01',
 'HLA-B57:01',
 'HLA-C03:04',
 'HLA-C07:02',
 'HLA-A30:01',
 'HLA-A32:01',
 'HLA-B40:02',
 'HLA-B51:01',
 'HLA-C02:02',
 'HLA-C16:02',
 'HLA-A30:01',
 'HLA-A02:01',
 'HLA-B35:03',
 'HLA-B44:03',
 'HLA-C15:02',
 'HLA-C02:02']

In [24]:
unique_all = list(set(all))

In [26]:
','.join(unique_all)

'HLA-B35:03,HLA-A30:04,HLA-B15:03,HLA-B44:02,HLA-C04:01,HLA-C02:10,HLA-A03:01,HLA-C12:02,HLA-B07:02,HLA-B51:01,HLA-A02:01,HLA-A30:01,HLA-B40:02,HLA-C16:01,HLA-C16:02,HLA-B35:01,HLA-A01:01,HLA-C05:01,HLA-C06:02,HLA-C02:02,HLA-A33:03,HLA-B15:01,HLA-C15:02,HLA-B51:08,HLA-B57:01,HLA-B52:01,HLA-C03:04,HLA-C07:02,HLA-A32:01,HLA-B44:03,HLA-A68:01,HLA-C03:03,HLA-B50:01'

In [27]:
len(unique_all)

33